// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indent/audit/v1/resources.proto

package auditv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Kind of Target the Event is being written to.
type Target_Kind int32

const (
	Target_INPUT  Target_Kind = 0
	Target_OUTPUT Target_Kind = 1
)

var Target_Kind_name = map[int32]string{
	0: "INPUT",
	1: "OUTPUT",
}

var Target_Kind_value = map[string]int32{
	"INPUT":  0,
	"OUTPUT": 1,
}

func (x Target_Kind) String() string {
	return proto.EnumName(Target_Kind_name, int32(x))
}

func (Target_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{3, 0}
}

// Actor is the entity that initiated the Event.
type Actor struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string            `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AltIds               []string          `protobuf:"bytes,3,rep,name=alt_ids,json=altIds,proto3" json:"alt_ids,omitempty"`
	Email                string            `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Kind                 string            `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Labels               map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Actor) Reset()         { *m = Actor{} }
func (m *Actor) String() string { return proto.CompactTextString(m) }
func (*Actor) ProtoMessage()    {}
func (*Actor) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{0}
}

func (m *Actor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actor.Unmarshal(m, b)
}
func (m *Actor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actor.Marshal(b, m, deterministic)
}
func (m *Actor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actor.Merge(m, src)
}
func (m *Actor) XXX_Size() int {
	return xxx_messageInfo_Actor.Size(m)
}
func (m *Actor) XXX_DiscardUnknown() {
	xxx_messageInfo_Actor.DiscardUnknown(m)
}

var xxx_messageInfo_Actor proto.InternalMessageInfo

func (m *Actor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Actor) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Actor) GetAltIds() []string {
	if m != nil {
		return m.AltIds
	}
	return nil
}

func (m *Actor) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Actor) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Actor) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// Event contains information captured at a specific moment of time, typically relating to an authorization decision or instance of access.
type Event struct {
	Event                string               `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string               `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId           string               `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	SessionId            string               `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Actor                *Actor               `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	Resources            []*Resource          `protobuf:"bytes,7,rep,name=resources,proto3" json:"resources,omitempty"`
	XOriginal            []byte               `protobuf:"bytes,8,opt,name=_original,json=Original,proto3" json:"_original,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Event) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Event) GetActor() *Actor {
	if m != nil {
		return m.Actor
	}
	return nil
}

func (m *Event) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Event) GetXOriginal() []byte {
	if m != nil {
		return m.XOriginal
	}
	return nil
}

// Resource related to the Event.
type Resource struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string            `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AltIds               []string          `protobuf:"bytes,3,rep,name=alt_ids,json=altIds,proto3" json:"alt_ids,omitempty"`
	Kind                 string            `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Labels               map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{2}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Resource) GetAltIds() []string {
	if m != nil {
		return m.AltIds
	}
	return nil
}

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Resource) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// Target is the intended recipient of the contained Events.
type Target struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 Target_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=indent.audit.v1.Target_Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{3}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetKind() Target_Kind {
	if m != nil {
		return m.Kind
	}
	return Target_INPUT
}

func init() {
	proto.RegisterEnum("indent.audit.v1.Target_Kind", Target_Kind_name, Target_Kind_value)
	proto.RegisterType((*Actor)(nil), "indent.audit.v1.Actor")
	proto.RegisterMapType((map[string]string)(nil), "indent.audit.v1.Actor.LabelsEntry")
	proto.RegisterType((*Event)(nil), "indent.audit.v1.Event")
	proto.RegisterType((*Resource)(nil), "indent.audit.v1.Resource")
	proto.RegisterMapType((map[string]string)(nil), "indent.audit.v1.Resource.LabelsEntry")
	proto.RegisterType((*Target)(nil), "indent.audit.v1.Target")
}

func init() { proto.RegisterFile("indent/audit/v1/resources.proto", fileDescriptor_3bf215d7d77adf9c) }

var fileDescriptor_3bf215d7d77adf9c = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xd1, 0x6a, 0xdb, 0x3c,
	0x18, 0xfd, 0x6d, 0xc7, 0x4e, 0xfc, 0xa5, 0xa4, 0x45, 0xff, 0xd8, 0xdc, 0x6c, 0x25, 0x59, 0x60,
	0x90, 0x8b, 0xe1, 0x2c, 0xd9, 0xc5, 0xba, 0xc2, 0x2e, 0x52, 0xe8, 0x85, 0xd9, 0x68, 0x83, 0x49,
	0xcb, 0x28, 0x85, 0xa0, 0x44, 0x5a, 0x10, 0xb5, 0xe5, 0x60, 0x29, 0x66, 0x79, 0x9d, 0x5d, 0x6e,
	0x6f, 0xb2, 0xe7, 0xd8, 0x23, 0xec, 0x01, 0x86, 0x25, 0x39, 0x2d, 0xe9, 0x76, 0xd7, 0x3b, 0x7d,
	0xe7, 0x3b, 0x47, 0x9c, 0xef, 0x70, 0xa0, 0xc3, 0x38, 0xa1, 0x5c, 0x0e, 0xf0, 0x9a, 0x30, 0x39,
	0x28, 0x86, 0x83, 0x9c, 0x8a, 0x6c, 0x9d, 0x2f, 0xa8, 0x08, 0x57, 0x79, 0x26, 0x33, 0xb4, 0xaf,
	0x09, 0xa1, 0x22, 0x84, 0xc5, 0xb0, 0x7d, 0xb8, 0xcc, 0xb2, 0x65, 0x42, 0x07, 0x6a, 0x3d, 0x5f,
	0x7f, 0x19, 0x60, 0xbe, 0xd1, 0xdc, 0x76, 0x67, 0x77, 0x25, 0x59, 0x4a, 0x85, 0xc4, 0xe9, 0x4a,
	0x13, 0x7a, 0xbf, 0x2d, 0x70, 0xc7, 0x0b, 0x99, 0xe5, 0xa8, 0x05, 0x36, 0x23, 0x81, 0xd5, 0xb5,
	0xfa, 0x7e, 0x6c, 0x33, 0x82, 0x5e, 0xc2, 0x1e, 0x61, 0x62, 0x95, 0xe0, 0xcd, 0x8c, 0xe3, 0x94,
	0x06, 0xb6, 0xda, 0x34, 0x0d, 0x76, 0x8e, 0x53, 0x8a, 0x9e, 0x41, 0x1d, 0x27, 0x72, 0xc6, 0x88,
	0x08, 0x9c, 0xae, 0xd3, 0xf7, 0x63, 0x0f, 0x27, 0x32, 0x22, 0x02, 0x3d, 0x01, 0x97, 0xa6, 0x98,
	0x25, 0x41, 0x4d, 0x89, 0xf4, 0x80, 0x10, 0xd4, 0x6e, 0x19, 0x27, 0x81, 0xab, 0x40, 0xf5, 0x46,
	0x27, 0xe0, 0x25, 0x78, 0x4e, 0x13, 0x11, 0x40, 0xd7, 0xe9, 0x37, 0x47, 0xbd, 0x70, 0xe7, 0xba,
	0x50, 0xb9, 0x0b, 0x3f, 0x29, 0xd2, 0x19, 0x97, 0xf9, 0x26, 0x36, 0x8a, 0xf6, 0x7b, 0x68, 0xde,
	0x83, 0xd1, 0x01, 0x38, 0xb7, 0x74, 0x63, 0x2e, 0x28, 0x9f, 0xa5, 0x8d, 0x02, 0x27, 0xeb, 0xca,
	0xbb, 0x1e, 0x4e, 0xec, 0x63, 0xab, 0xf7, 0xc3, 0x06, 0xf7, 0xac, 0xa0, 0x5c, 0x2a, 0xab, 0xe5,
	0xc3, 0xe8, 0xf4, 0x80, 0x8e, 0xc1, 0xdf, 0x26, 0xa5, 0xd4, 0xcd, 0x51, 0x3b, 0xd4, 0x59, 0x86,
	0x55, 0x96, 0xe1, 0xb4, 0x62, 0xc4, 0x77, 0x64, 0x13, 0xa3, 0xb3, 0x8d, 0xb1, 0x03, 0x4d, 0xfa,
	0x55, 0xd2, 0x9c, 0xe3, 0x64, 0xc6, 0x88, 0x09, 0x04, 0x2a, 0x28, 0x22, 0xe8, 0x08, 0x40, 0x50,
	0x21, 0x58, 0xc6, 0xcb, 0xbd, 0xce, 0xc6, 0x37, 0x48, 0x44, 0xd0, 0x6b, 0x70, 0x71, 0x99, 0x40,
	0xe0, 0x29, 0x17, 0x4f, 0xff, 0x9e, 0x4f, 0xac, 0x49, 0xe8, 0x1d, 0xf8, 0xdb, 0xba, 0x04, 0x75,
	0x95, 0xe8, 0xe1, 0x03, 0x45, 0x6c, 0x18, 0xf1, 0x1d, 0x17, 0x3d, 0x07, 0x7f, 0x96, 0xe5, 0x6c,
	0xc9, 0x38, 0x4e, 0x82, 0x46, 0xd7, 0xea, 0xef, 0xc5, 0x8d, 0x0b, 0x33, 0xf7, 0x7e, 0x59, 0xd0,
	0xa8, 0x44, 0x8f, 0xda, 0x93, 0xaa, 0x11, 0xb5, 0x7b, 0x8d, 0xf8, 0xb0, 0xd3, 0x88, 0x57, 0xff,
	0xf4, 0xff, 0xd8, 0xa5, 0x48, 0xc1, 0x9b, 0xe2, 0x7c, 0x49, 0x65, 0xe9, 0x4b, 0xdd, 0xa2, 0x65,
	0xea, 0x8d, 0xde, 0x18, 0xaf, 0xa5, 0xac, 0x35, 0x7a, 0xf1, 0xc0, 0x95, 0x96, 0x86, 0x1f, 0x19,
	0x27, 0xfa, 0x92, 0xde, 0x11, 0xd4, 0xca, 0x09, 0xf9, 0xe0, 0x46, 0xe7, 0x93, 0xcb, 0xe9, 0xc1,
	0x7f, 0x08, 0xc0, 0xbb, 0xb8, 0x9c, 0x96, 0x6f, 0xeb, 0xf4, 0x1a, 0xfe, 0x5f, 0x64, 0xe9, 0xee,
	0x3f, 0xa7, 0xad, 0xea, 0x3c, 0x31, 0x29, 0x8b, 0x36, 0xb1, 0xae, 0xeb, 0x6a, 0x57, 0x0c, 0xbf,
	0xd9, 0x4e, 0x34, 0xfe, 0xfc, 0xdd, 0xde, 0x8f, 0xb4, 0x64, 0xac, 0x24, 0x57, 0xc3, 0x9f, 0x15,
	0x72, 0xa3, 0x90, 0x9b, 0xab, 0xe1, 0xdc, 0x53, 0x25, 0x7d, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0xdf, 0x93, 0x7b, 0x4d, 0x04, 0x00, 0x00,
}
