// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indent/audit/v1/resources.proto

package auditv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Kind of Target the Event is being written to.
type Target_Kind int32

const (
	Target_INPUT  Target_Kind = 0
	Target_OUTPUT Target_Kind = 1
)

var Target_Kind_name = map[int32]string{
	0: "INPUT",
	1: "OUTPUT",
}

var Target_Kind_value = map[string]int32{
	"INPUT":  0,
	"OUTPUT": 1,
}

func (x Target_Kind) String() string {
	return proto.EnumName(Target_Kind_name, int32(x))
}

func (Target_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{3, 0}
}

// Event contains information captured at a specific moment of time, typically relating to an authorization decision or instance of access.
type Event struct {
	Event                string               `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Meta                 *Meta                `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Reason               string               `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string               `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId           string               `protobuf:"bytes,13,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	SessionId            string               `protobuf:"bytes,20,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Actor                *Resource            `protobuf:"bytes,27,opt,name=actor,proto3" json:"actor,omitempty"`
	Resources            []*Resource          `protobuf:"bytes,30,rep,name=resources,proto3" json:"resources,omitempty"`
	XOriginal            []byte               `protobuf:"bytes,35,opt,name=_original,json=Original,proto3" json:"_original,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Event) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Event) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Event) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Event) GetActor() *Resource {
	if m != nil {
		return m.Actor
	}
	return nil
}

func (m *Event) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Event) GetXOriginal() []byte {
	if m != nil {
		return m.XOriginal
	}
	return nil
}

// Meta contains metadata about an Event.
type Meta struct {
	Labels               map[string]string `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{1}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// Resource related to the Event.
type Resource struct {
	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AltIds      []string `protobuf:"bytes,3,rep,name=alt_ids,json=altIds,proto3" json:"alt_ids,omitempty"`
	Kind        string   `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Email       string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// Arbitrary string-addressable labels
	Labels               map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{2}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Resource) GetAltIds() []string {
	if m != nil {
		return m.AltIds
	}
	return nil
}

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Resource) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Resource) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// Target is the intended recipient of the contained Events.
type Target struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 Target_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=indent.audit.v1.Target_Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf215d7d77adf9c, []int{3}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetKind() Target_Kind {
	if m != nil {
		return m.Kind
	}
	return Target_INPUT
}

func init() {
	proto.RegisterEnum("indent.audit.v1.Target_Kind", Target_Kind_name, Target_Kind_value)
	proto.RegisterType((*Event)(nil), "indent.audit.v1.Event")
	proto.RegisterType((*Meta)(nil), "indent.audit.v1.Meta")
	proto.RegisterMapType((map[string]string)(nil), "indent.audit.v1.Meta.LabelsEntry")
	proto.RegisterType((*Resource)(nil), "indent.audit.v1.Resource")
	proto.RegisterMapType((map[string]string)(nil), "indent.audit.v1.Resource.LabelsEntry")
	proto.RegisterType((*Target)(nil), "indent.audit.v1.Target")
}

func init() {
	proto.RegisterFile("indent/audit/v1/resources.proto", fileDescriptor_3bf215d7d77adf9c)
}

var fileDescriptor_3bf215d7d77adf9c = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0x92, 0xd6, 0x93, 0xd2, 0x56, 0x4b, 0x81, 0x6d, 0x4a, 0x69, 0x1a, 0x84, 0x54,
	0x2e, 0x36, 0x29, 0x07, 0x5a, 0x24, 0x0e, 0xad, 0xd4, 0x83, 0x05, 0xb4, 0x95, 0x95, 0x56, 0xa8,
	0xaa, 0x14, 0x6d, 0xb2, 0x4b, 0xb4, 0xaa, 0xbd, 0x8e, 0xbc, 0x9b, 0x88, 0x48, 0xfc, 0x1a, 0x8e,
	0xfc, 0x14, 0xfe, 0x0d, 0x57, 0x4e, 0x68, 0xc7, 0x76, 0x8a, 0x52, 0xe0, 0xc4, 0x6d, 0x3e, 0xde,
	0x1b, 0xcf, 0x7b, 0xb3, 0x86, 0x1d, 0xa9, 0xb8, 0x50, 0x26, 0x64, 0x13, 0x2e, 0x4d, 0x38, 0xed,
	0x86, 0xb9, 0xd0, 0xd9, 0x24, 0x1f, 0x0a, 0x1d, 0x8c, 0xf3, 0xcc, 0x64, 0x64, 0xad, 0x00, 0x04,
	0x08, 0x08, 0xa6, 0xdd, 0xd6, 0xe6, 0x28, 0xcb, 0x46, 0x89, 0x08, 0xb1, 0x3d, 0x98, 0x7c, 0x0a,
	0x99, 0x9a, 0x15, 0xd8, 0xd6, 0xce, 0x62, 0xcb, 0xc8, 0x54, 0x68, 0xc3, 0xd2, 0x71, 0x01, 0xe8,
	0xfc, 0x70, 0xa1, 0x7e, 0x32, 0x15, 0xca, 0x90, 0x0d, 0xa8, 0x0b, 0x1b, 0x50, 0xa7, 0xed, 0xec,
	0xf9, 0x71, 0x91, 0x90, 0x17, 0x50, 0x4b, 0x85, 0x61, 0xd4, 0x6d, 0x3b, 0x7b, 0xcd, 0xfd, 0x87,
	0xc1, 0xc2, 0xb7, 0x83, 0x0f, 0xc2, 0xb0, 0x18, 0x21, 0xe4, 0x11, 0x34, 0x72, 0xc1, 0x74, 0xa6,
	0xa8, 0x87, 0x13, 0xca, 0x8c, 0x1c, 0x80, 0x3f, 0xff, 0x2a, 0xad, 0xe3, 0x9c, 0x56, 0x50, 0xec,
	0x15, 0x54, 0x7b, 0x05, 0xbd, 0x0a, 0x11, 0xdf, 0x82, 0xc9, 0x2a, 0xb8, 0x92, 0x53, 0x1f, 0xa7,
	0xb9, 0x92, 0x93, 0x1d, 0x68, 0x8a, 0xcf, 0x46, 0xe4, 0x8a, 0x25, 0x7d, 0xc9, 0xe9, 0x7d, 0x6c,
	0x40, 0x55, 0x8a, 0x38, 0xd9, 0x06, 0xd0, 0x42, 0x6b, 0x99, 0x29, 0xdb, 0xdf, 0xc0, 0xbe, 0x5f,
	0x56, 0x22, 0x4e, 0x42, 0xa8, 0xb3, 0xa1, 0xc9, 0x72, 0xba, 0x85, 0x5b, 0x6c, 0xde, 0x51, 0x13,
	0x97, 0x56, 0xc7, 0x05, 0x8e, 0xbc, 0x06, 0x7f, 0xee, 0x3e, 0x7d, 0xda, 0xf6, 0xfe, 0x4d, 0xba,
	0xc5, 0x92, 0x2d, 0xf0, 0xfb, 0x59, 0x2e, 0x47, 0x52, 0xb1, 0x84, 0x3e, 0x6b, 0x3b, 0x7b, 0x2b,
	0xf1, 0xf2, 0x59, 0x99, 0x77, 0xbe, 0x40, 0xcd, 0xda, 0x46, 0x0e, 0xa1, 0x91, 0xb0, 0x81, 0x48,
	0x34, 0xdd, 0xc0, 0xd1, 0xbb, 0x7f, 0x74, 0x37, 0x78, 0x8f, 0x98, 0x13, 0x65, 0xf2, 0x59, 0x5c,
	0x12, 0x5a, 0x87, 0xd0, 0xfc, 0xad, 0x4c, 0xd6, 0xc1, 0xbb, 0x11, 0xb3, 0xf2, 0x72, 0x36, 0xb4,
	0xd7, 0x9c, 0xb2, 0x64, 0x22, 0xf0, 0x70, 0x7e, 0x5c, 0x24, 0x6f, 0xdc, 0x03, 0xa7, 0xf3, 0xd3,
	0x81, 0xe5, 0x6a, 0xe5, 0xd2, 0x61, 0x67, 0xee, 0xf0, 0x2e, 0xac, 0x70, 0xa9, 0xc7, 0x09, 0x9b,
	0xf5, 0x15, 0x4b, 0x2b, 0x76, 0xb3, 0xac, 0x9d, 0xb2, 0x54, 0x90, 0xc7, 0xb0, 0xc4, 0x12, 0xd3,
	0x97, 0x5c, 0x53, 0xaf, 0xed, 0xd9, 0x3b, 0xb3, 0xc4, 0x44, 0x5c, 0x13, 0x02, 0xb5, 0x1b, 0xa9,
	0x38, 0xad, 0x21, 0x07, 0x63, 0x7c, 0x54, 0x29, 0x93, 0x09, 0xde, 0xdd, 0x3e, 0x2a, 0x9b, 0x90,
	0xb7, 0x73, 0xe1, 0x80, 0xc2, 0x9f, 0xff, 0xd5, 0xd3, 0xff, 0x2d, 0x3e, 0x85, 0x46, 0x8f, 0xe5,
	0x23, 0x61, 0xec, 0xb6, 0xa8, 0xb0, 0xa0, 0x61, 0x4c, 0x5e, 0x96, 0x0a, 0x2c, 0x6d, 0x75, 0xff,
	0xc9, 0x9d, 0xad, 0x0a, 0x6a, 0xf0, 0x4e, 0x2a, 0x5e, 0xe8, 0xeb, 0x6c, 0x43, 0xcd, 0x66, 0xc4,
	0x87, 0x7a, 0x74, 0x7a, 0x7e, 0xd1, 0x5b, 0xbf, 0x47, 0x00, 0x1a, 0x67, 0x17, 0x3d, 0x1b, 0x3b,
	0xc7, 0x57, 0xf0, 0x60, 0x98, 0xa5, 0x8b, 0x73, 0x8e, 0x57, 0x2b, 0x79, 0xfa, 0xdc, 0xbe, 0xff,
	0x73, 0xe7, 0x6a, 0x09, 0x7b, 0xd3, 0xee, 0x57, 0xd7, 0x8b, 0x8e, 0x3e, 0x7e, 0x73, 0xd7, 0xa2,
	0x82, 0x72, 0x84, 0x94, 0xcb, 0xee, 0xf7, 0xaa, 0x72, 0x8d, 0x95, 0xeb, 0xcb, 0xee, 0xa0, 0x81,
	0xff, 0xce, 0xab, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x08, 0xc5, 0xc4, 0x12, 0x30, 0x04, 0x00,
	0x00,
}
