// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indent/v1/account_api.proto

package indentv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "go.indent.com/indent-go/api/indent/audit/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOnboardingRequest struct {
	// Space in which onboarding is happening.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Onboarding object needed to populate onboarding notification.
	Onboarding           *Onboarding `protobuf:"bytes,5,opt,name=onboarding,proto3" json:"onboarding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateOnboardingRequest) Reset()         { *m = CreateOnboardingRequest{} }
func (m *CreateOnboardingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOnboardingRequest) ProtoMessage()    {}
func (*CreateOnboardingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{0}
}

func (m *CreateOnboardingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOnboardingRequest.Unmarshal(m, b)
}
func (m *CreateOnboardingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOnboardingRequest.Marshal(b, m, deterministic)
}
func (m *CreateOnboardingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOnboardingRequest.Merge(m, src)
}
func (m *CreateOnboardingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOnboardingRequest.Size(m)
}
func (m *CreateOnboardingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOnboardingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOnboardingRequest proto.InternalMessageInfo

func (m *CreateOnboardingRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *CreateOnboardingRequest) GetOnboarding() *Onboarding {
	if m != nil {
		return m.Onboarding
	}
	return nil
}

type CreateOnboardingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOnboardingResponse) Reset()         { *m = CreateOnboardingResponse{} }
func (m *CreateOnboardingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOnboardingResponse) ProtoMessage()    {}
func (*CreateOnboardingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{1}
}

func (m *CreateOnboardingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOnboardingResponse.Unmarshal(m, b)
}
func (m *CreateOnboardingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOnboardingResponse.Marshal(b, m, deterministic)
}
func (m *CreateOnboardingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOnboardingResponse.Merge(m, src)
}
func (m *CreateOnboardingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOnboardingResponse.Size(m)
}
func (m *CreateOnboardingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOnboardingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOnboardingResponse proto.InternalMessageInfo

type Onboarding struct {
	// Targets to be onboarding.
	Targets []*v1.Resource `protobuf:"bytes,15,rep,name=targets,proto3" json:"targets,omitempty"`
	// Resources to show user as part of onboarding.
	Resources []*v1.Resource `protobuf:"bytes,25,rep,name=resources,proto3" json:"resources,omitempty"`
	// Message to be optionally displayed to the user.
	Message              string   `protobuf:"bytes,35,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Onboarding) Reset()         { *m = Onboarding{} }
func (m *Onboarding) String() string { return proto.CompactTextString(m) }
func (*Onboarding) ProtoMessage()    {}
func (*Onboarding) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{2}
}

func (m *Onboarding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Onboarding.Unmarshal(m, b)
}
func (m *Onboarding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Onboarding.Marshal(b, m, deterministic)
}
func (m *Onboarding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Onboarding.Merge(m, src)
}
func (m *Onboarding) XXX_Size() int {
	return xxx_messageInfo_Onboarding.Size(m)
}
func (m *Onboarding) XXX_DiscardUnknown() {
	xxx_messageInfo_Onboarding.DiscardUnknown(m)
}

var xxx_messageInfo_Onboarding proto.InternalMessageInfo

func (m *Onboarding) GetTargets() []*v1.Resource {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *Onboarding) GetResources() []*v1.Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Onboarding) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListSpacesRequest struct {
	// Name of the parent whose children should be listed.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Max number of Spaces to be returned.
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSpacesRequest) Reset()         { *m = ListSpacesRequest{} }
func (m *ListSpacesRequest) String() string { return proto.CompactTextString(m) }
func (*ListSpacesRequest) ProtoMessage()    {}
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{3}
}

func (m *ListSpacesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSpacesRequest.Unmarshal(m, b)
}
func (m *ListSpacesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSpacesRequest.Marshal(b, m, deterministic)
}
func (m *ListSpacesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSpacesRequest.Merge(m, src)
}
func (m *ListSpacesRequest) XXX_Size() int {
	return xxx_messageInfo_ListSpacesRequest.Size(m)
}
func (m *ListSpacesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSpacesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSpacesRequest proto.InternalMessageInfo

func (m *ListSpacesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListSpacesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListSpacesResponse struct {
	// Paginated list of Spaces that are children of the parent resource.
	Spaces               []*Space `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSpacesResponse) Reset()         { *m = ListSpacesResponse{} }
func (m *ListSpacesResponse) String() string { return proto.CompactTextString(m) }
func (*ListSpacesResponse) ProtoMessage()    {}
func (*ListSpacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{4}
}

func (m *ListSpacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSpacesResponse.Unmarshal(m, b)
}
func (m *ListSpacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSpacesResponse.Marshal(b, m, deterministic)
}
func (m *ListSpacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSpacesResponse.Merge(m, src)
}
func (m *ListSpacesResponse) XXX_Size() int {
	return xxx_messageInfo_ListSpacesResponse.Size(m)
}
func (m *ListSpacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSpacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSpacesResponse proto.InternalMessageInfo

func (m *ListSpacesResponse) GetSpaces() []*Space {
	if m != nil {
		return m.Spaces
	}
	return nil
}

type GetSpaceRequest struct {
	// Resource name of Space to retrieve.
	SpaceName            string   `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpaceRequest) Reset()         { *m = GetSpaceRequest{} }
func (m *GetSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpaceRequest) ProtoMessage()    {}
func (*GetSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{5}
}

func (m *GetSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpaceRequest.Unmarshal(m, b)
}
func (m *GetSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpaceRequest.Marshal(b, m, deterministic)
}
func (m *GetSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpaceRequest.Merge(m, src)
}
func (m *GetSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpaceRequest.Size(m)
}
func (m *GetSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpaceRequest proto.InternalMessageInfo

func (m *GetSpaceRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

type CreateSpaceRequest struct {
	// Space being created.
	Space                *Space   `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSpaceRequest) Reset()         { *m = CreateSpaceRequest{} }
func (m *CreateSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSpaceRequest) ProtoMessage()    {}
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{6}
}

func (m *CreateSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSpaceRequest.Unmarshal(m, b)
}
func (m *CreateSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSpaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSpaceRequest.Merge(m, src)
}
func (m *CreateSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSpaceRequest.Size(m)
}
func (m *CreateSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSpaceRequest proto.InternalMessageInfo

func (m *CreateSpaceRequest) GetSpace() *Space {
	if m != nil {
		return m.Space
	}
	return nil
}

type UpdateSpaceRequest struct {
	// Resource name of Space to update.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Space with changes to be implemented.
	Space                *Space   `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpaceRequest) Reset()         { *m = UpdateSpaceRequest{} }
func (m *UpdateSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSpaceRequest) ProtoMessage()    {}
func (*UpdateSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{7}
}

func (m *UpdateSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpaceRequest.Unmarshal(m, b)
}
func (m *UpdateSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpaceRequest.Merge(m, src)
}
func (m *UpdateSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSpaceRequest.Size(m)
}
func (m *UpdateSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpaceRequest proto.InternalMessageInfo

func (m *UpdateSpaceRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *UpdateSpaceRequest) GetSpace() *Space {
	if m != nil {
		return m.Space
	}
	return nil
}

type DeleteSpaceRequest struct {
	// Name of the Space to be deleted.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Space's children and it's children's children are deleted.
	Recursive            bool     `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSpaceRequest) Reset()         { *m = DeleteSpaceRequest{} }
func (m *DeleteSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSpaceRequest) ProtoMessage()    {}
func (*DeleteSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{8}
}

func (m *DeleteSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSpaceRequest.Unmarshal(m, b)
}
func (m *DeleteSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSpaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSpaceRequest.Merge(m, src)
}
func (m *DeleteSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSpaceRequest.Size(m)
}
func (m *DeleteSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSpaceRequest proto.InternalMessageInfo

func (m *DeleteSpaceRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *DeleteSpaceRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

// Space in a Organization's hierarchy.
type Space struct {
	// Resource name of a Space.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Name of parent of Space.
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Text that should be shown to users to represent a Space.
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Space) Reset()         { *m = Space{} }
func (m *Space) String() string { return proto.CompactTextString(m) }
func (*Space) ProtoMessage()    {}
func (*Space) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{9}
}

func (m *Space) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Space.Unmarshal(m, b)
}
func (m *Space) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Space.Marshal(b, m, deterministic)
}
func (m *Space) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Space.Merge(m, src)
}
func (m *Space) XXX_Size() int {
	return xxx_messageInfo_Space.Size(m)
}
func (m *Space) XXX_DiscardUnknown() {
	xxx_messageInfo_Space.DiscardUnknown(m)
}

var xxx_messageInfo_Space proto.InternalMessageInfo

func (m *Space) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Space) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Space) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type SetPolicyRequest struct {
	// Resource whose Policy is being changed.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Policy being set for a resource.
	Policy               *Policy  `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPolicyRequest) Reset()         { *m = SetPolicyRequest{} }
func (m *SetPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*SetPolicyRequest) ProtoMessage()    {}
func (*SetPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{10}
}

func (m *SetPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPolicyRequest.Unmarshal(m, b)
}
func (m *SetPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPolicyRequest.Marshal(b, m, deterministic)
}
func (m *SetPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPolicyRequest.Merge(m, src)
}
func (m *SetPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_SetPolicyRequest.Size(m)
}
func (m *SetPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPolicyRequest proto.InternalMessageInfo

func (m *SetPolicyRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *SetPolicyRequest) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

type GetPolicyRequest struct {
	// Resource whose Policy is being requested.
	Resource             string   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPolicyRequest) Reset()         { *m = GetPolicyRequest{} }
func (m *GetPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*GetPolicyRequest) ProtoMessage()    {}
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{11}
}

func (m *GetPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPolicyRequest.Unmarshal(m, b)
}
func (m *GetPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPolicyRequest.Marshal(b, m, deterministic)
}
func (m *GetPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPolicyRequest.Merge(m, src)
}
func (m *GetPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_GetPolicyRequest.Size(m)
}
func (m *GetPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPolicyRequest proto.InternalMessageInfo

func (m *GetPolicyRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

// Policy contains a set of bindings which associate accounts with roles within a resource.
type Policy struct {
	// Bindings associating accounts with roles.
	Bindings             []*Binding `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_88e2c317f0525db1, []int{12}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetBindings() []*Binding {
	if m != nil {
		return m.Bindings
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateOnboardingRequest)(nil), "indent.v1.CreateOnboardingRequest")
	proto.RegisterType((*CreateOnboardingResponse)(nil), "indent.v1.CreateOnboardingResponse")
	proto.RegisterType((*Onboarding)(nil), "indent.v1.Onboarding")
	proto.RegisterType((*ListSpacesRequest)(nil), "indent.v1.ListSpacesRequest")
	proto.RegisterType((*ListSpacesResponse)(nil), "indent.v1.ListSpacesResponse")
	proto.RegisterType((*GetSpaceRequest)(nil), "indent.v1.GetSpaceRequest")
	proto.RegisterType((*CreateSpaceRequest)(nil), "indent.v1.CreateSpaceRequest")
	proto.RegisterType((*UpdateSpaceRequest)(nil), "indent.v1.UpdateSpaceRequest")
	proto.RegisterType((*DeleteSpaceRequest)(nil), "indent.v1.DeleteSpaceRequest")
	proto.RegisterType((*Space)(nil), "indent.v1.Space")
	proto.RegisterType((*SetPolicyRequest)(nil), "indent.v1.SetPolicyRequest")
	proto.RegisterType((*GetPolicyRequest)(nil), "indent.v1.GetPolicyRequest")
	proto.RegisterType((*Policy)(nil), "indent.v1.Policy")
}

func init() {
	proto.RegisterFile("indent/v1/account_api.proto", fileDescriptor_88e2c317f0525db1)
}

var fileDescriptor_88e2c317f0525db1 = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0xe5, 0x4a, 0x16, 0x47, 0x2e, 0x24, 0x0f, 0xe0, 0x9a, 0xa2, 0x65, 0x58, 0x5d, 0x17,
	0x85, 0xea, 0x83, 0x54, 0xc9, 0x28, 0x5a, 0xb8, 0x45, 0x01, 0xbb, 0x05, 0x54, 0x03, 0x45, 0xab,
	0xd2, 0xb5, 0x61, 0xe7, 0x07, 0xc2, 0x4a, 0x5a, 0x10, 0x04, 0x24, 0x92, 0xe1, 0x52, 0x02, 0xec,
	0xc0, 0x97, 0x5c, 0x73, 0x4c, 0x9e, 0x20, 0xc7, 0x3c, 0x46, 0x8e, 0xb9, 0xe6, 0x15, 0xf2, 0x20,
	0x01, 0x97, 0x7f, 0x2b, 0x51, 0xb2, 0x63, 0xe4, 0xc6, 0xdd, 0xf9, 0xe6, 0xfb, 0x66, 0x66, 0xbf,
	0xe5, 0xc2, 0x8e, 0x65, 0x8f, 0x98, 0xed, 0xb7, 0x66, 0xed, 0x16, 0x1d, 0x0e, 0x9d, 0xa9, 0xed,
	0xf7, 0xa9, 0x6b, 0x35, 0x5d, 0xcf, 0xf1, 0x1d, 0x54, 0xc3, 0x60, 0x73, 0xd6, 0xd6, 0x6b, 0xa6,
	0xe3, 0x98, 0x63, 0xd6, 0xa2, 0xae, 0xd5, 0xa2, 0xb6, 0xed, 0xf8, 0xd4, 0xb7, 0x1c, 0x9b, 0x87,
	0x40, 0x7d, 0x2f, 0x62, 0xa1, 0xd3, 0x91, 0x25, 0xb8, 0x3c, 0xc6, 0x9d, 0xa9, 0x37, 0x64, 0x31,
	0xa0, 0x9a, 0xca, 0x2c, 0x84, 0x88, 0x03, 0xdb, 0x7f, 0x78, 0x8c, 0xfa, 0xec, 0x5f, 0x7b, 0xe0,
	0x50, 0x6f, 0x64, 0xd9, 0xa6, 0xc1, 0x9e, 0x4d, 0x19, 0xf7, 0x71, 0x17, 0x80, 0xbb, 0x74, 0xc8,
	0xfa, 0x36, 0x9d, 0x30, 0x4d, 0xa9, 0x2b, 0x0d, 0xd5, 0x50, 0xc5, 0xce, 0x3f, 0x74, 0xc2, 0xf0,
	0x27, 0x00, 0x27, 0xc9, 0xd1, 0xf2, 0x75, 0xa5, 0x51, 0xea, 0x6c, 0x35, 0x93, 0x9a, 0x9b, 0x12,
	0xa1, 0x04, 0x24, 0x3a, 0x68, 0x59, 0x41, 0xee, 0x3a, 0x36, 0x67, 0xe4, 0xb5, 0x02, 0x90, 0x6e,
	0xe3, 0x21, 0xac, 0xfb, 0xd4, 0x33, 0x99, 0xcf, 0xb5, 0x72, 0x7d, 0xad, 0x51, 0xea, 0x54, 0x63,
	0x7a, 0xd1, 0x69, 0x20, 0x62, 0x44, 0xed, 0x18, 0x31, 0x12, 0x7f, 0x06, 0x35, 0xe9, 0x51, 0xab,
	0xde, 0x97, 0x96, 0x62, 0x51, 0x83, 0xf5, 0x09, 0xe3, 0x9c, 0x9a, 0x4c, 0xdb, 0x17, 0xbd, 0xc6,
	0x4b, 0xf2, 0x17, 0x6c, 0xfe, 0x6d, 0x71, 0xff, 0x2c, 0x68, 0x9d, 0xc7, 0xd3, 0xf9, 0x06, 0x0a,
	0x2e, 0xf5, 0x98, 0xed, 0x47, 0x93, 0x89, 0x56, 0xb8, 0x03, 0xaa, 0x4b, 0x4d, 0xd6, 0xe7, 0xd6,
	0x0d, 0xd3, 0x72, 0x75, 0xa5, 0x91, 0x37, 0x8a, 0xc1, 0xc6, 0x99, 0x75, 0xc3, 0xc8, 0xef, 0x80,
	0x32, 0x53, 0xd8, 0x36, 0x36, 0xa0, 0x20, 0xc6, 0xca, 0x35, 0x45, 0xd4, 0x5b, 0x91, 0xa6, 0x28,
	0xa0, 0x46, 0x14, 0x27, 0x3f, 0x42, 0xb9, 0xcb, 0xc2, 0xf4, 0xcf, 0x3b, 0x25, 0xf2, 0x1b, 0x60,
	0x38, 0xee, 0xb9, 0xa4, 0xef, 0x21, 0x2f, 0x20, 0x02, 0xbf, 0x4c, 0x30, 0x0c, 0x93, 0xc7, 0x80,
	0xe7, 0xee, 0x68, 0x31, 0xfb, 0x1e, 0x63, 0x24, 0xe4, 0xb9, 0xbb, 0xc9, 0xff, 0x03, 0xfc, 0x93,
	0x8d, 0xd9, 0xc3, 0xc8, 0x6b, 0xc1, 0xf1, 0x0e, 0xa7, 0x1e, 0xb7, 0x66, 0xa1, 0x40, 0xd1, 0x48,
	0x37, 0xc8, 0x05, 0xe4, 0x05, 0x19, 0x22, 0x7c, 0x25, 0xe5, 0x8b, 0x6f, 0xe9, 0xc4, 0x72, 0x73,
	0x27, 0xf6, 0x2d, 0x6c, 0x8c, 0x2c, 0xee, 0x8e, 0xe9, 0x75, 0xa8, 0xb9, 0x26, 0xa2, 0xa5, 0x68,
	0x4f, 0x4c, 0xf1, 0x0a, 0x2a, 0x67, 0xcc, 0xef, 0x39, 0x63, 0x6b, 0x78, 0x1d, 0x17, 0xaa, 0x43,
	0x31, 0x36, 0x4f, 0x24, 0x93, 0xac, 0xf1, 0x07, 0x28, 0xb8, 0x02, 0x1c, 0xcd, 0x60, 0x53, 0x9a,
	0x41, 0xc4, 0x12, 0x01, 0x48, 0x13, 0x2a, 0xdd, 0x07, 0x50, 0x93, 0x5f, 0xa0, 0x10, 0x82, 0xb1,
	0x09, 0xc5, 0x81, 0x65, 0x07, 0x37, 0x85, 0x6b, 0x39, 0x61, 0x1c, 0x94, 0x64, 0x4e, 0xc2, 0x90,
	0x91, 0x60, 0x3a, 0xef, 0x0a, 0x00, 0xc7, 0xe1, 0x5f, 0xe6, 0xb8, 0x77, 0x8a, 0x4f, 0x01, 0x52,
	0x2f, 0x62, 0x4d, 0x4a, 0xcd, 0x98, 0x5d, 0xdf, 0x5d, 0x11, 0x8d, 0xee, 0x2d, 0xbe, 0xf8, 0xf0,
	0xf1, 0x55, 0x6e, 0x03, 0x21, 0xf8, 0xc3, 0x84, 0x56, 0xc5, 0x2b, 0x28, 0xc6, 0x56, 0x45, 0x5d,
	0x4a, 0x5f, 0xf0, 0xaf, 0x9e, 0xb1, 0x07, 0xd9, 0x13, 0x6c, 0x55, 0xdc, 0x4e, 0xd9, 0x5a, 0xcf,
	0x53, 0x4f, 0xdc, 0xe2, 0x39, 0x94, 0x24, 0x4f, 0xa3, 0x5c, 0x5c, 0xd6, 0xeb, 0x4b, 0x04, 0xb6,
	0x84, 0x40, 0x99, 0x48, 0xe5, 0x1e, 0x29, 0x07, 0x38, 0x80, 0x92, 0x64, 0xf6, 0x39, 0xda, 0xec,
	0x25, 0x58, 0x42, 0x4b, 0x04, 0x6d, 0xad, 0xb3, 0xaa, 0xee, 0x40, 0xa3, 0x0f, 0x25, 0xc9, 0xf3,
	0x73, 0x1a, 0xd9, 0xbb, 0xb0, 0x7a, 0x36, 0x07, 0x2b, 0x67, 0x63, 0x82, 0x9a, 0x38, 0x15, 0x77,
	0xe4, 0xfc, 0x05, 0x93, 0xe9, 0x59, 0x4f, 0x92, 0x03, 0xc1, 0xfe, 0x1d, 0xd9, 0x93, 0xd9, 0x63,
	0xe7, 0xdd, 0x1e, 0xf1, 0x98, 0x22, 0xe8, 0xc4, 0x04, 0xb5, 0xbb, 0x54, 0xa8, 0xfb, 0xe5, 0x42,
	0xa6, 0x2c, 0xf4, 0x52, 0x81, 0xca, 0xe2, 0x8b, 0x81, 0x24, 0x73, 0xe6, 0x99, 0xf7, 0x4b, 0xdf,
	0xbf, 0x13, 0x13, 0x59, 0xb7, 0x29, 0x2a, 0x69, 0x90, 0xfd, 0x15, 0x03, 0x6d, 0xa5, 0x4f, 0x57,
	0x60, 0x92, 0x93, 0xff, 0xe1, 0xeb, 0xa1, 0x33, 0x49, 0x99, 0x4f, 0xca, 0xf1, 0x95, 0x72, 0xad,
	0x5e, 0xf0, 0xa2, 0xf6, 0x94, 0x47, 0x98, 0x3c, 0xb7, 0xbf, 0x86, 0x5f, 0xb3, 0xf6, 0x9b, 0xdc,
	0xda, 0xe9, 0xe5, 0xe5, 0xdb, 0x9c, 0x7a, 0x1a, 0x26, 0x5e, 0xb4, 0xdf, 0xc7, 0xdf, 0x4f, 0x2e,
	0xda, 0x83, 0x82, 0x78, 0x8c, 0x0f, 0x3f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x48, 0xa8, 0x36, 0x9b,
	0x10, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountAPIClient is the client API for AccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountAPIClient interface {
	// List the Spaces that are children of given parent.
	ListSpaces(ctx context.Context, in *ListSpacesRequest, opts ...grpc.CallOption) (*ListSpacesResponse, error)
	// Retrieve specified space by name.
	GetSpace(ctx context.Context, in *GetSpaceRequest, opts ...grpc.CallOption) (*Space, error)
	// Create a new Space to contain resources.
	CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*Space, error)
	// Update configuration of a Space.
	UpdateSpace(ctx context.Context, in *UpdateSpaceRequest, opts ...grpc.CallOption) (*Space, error)
	// Permanently destroy a Space.
	DeleteSpace(ctx context.Context, in *DeleteSpaceRequest, opts ...grpc.CallOption) (*Space, error)
	// SetPolicy for permissions in a Space.
	SetPolicy(ctx context.Context, in *SetPolicyRequest, opts ...grpc.CallOption) (*Policy, error)
	// GetPolicy for permissions in a Space.
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*Policy, error)
	// CreateOnboarding notifies a user to initiate their onboarding to a Space.
	CreateOnboarding(ctx context.Context, in *CreateOnboardingRequest, opts ...grpc.CallOption) (*CreateOnboardingResponse, error)
}

type accountAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountAPIClient(cc grpc.ClientConnInterface) AccountAPIClient {
	return &accountAPIClient{cc}
}

func (c *accountAPIClient) ListSpaces(ctx context.Context, in *ListSpacesRequest, opts ...grpc.CallOption) (*ListSpacesResponse, error) {
	out := new(ListSpacesResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/ListSpaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetSpace(ctx context.Context, in *GetSpaceRequest, opts ...grpc.CallOption) (*Space, error) {
	out := new(Space)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/GetSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*Space, error) {
	out := new(Space)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/CreateSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) UpdateSpace(ctx context.Context, in *UpdateSpaceRequest, opts ...grpc.CallOption) (*Space, error) {
	out := new(Space)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/UpdateSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) DeleteSpace(ctx context.Context, in *DeleteSpaceRequest, opts ...grpc.CallOption) (*Space, error) {
	out := new(Space)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/DeleteSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) SetPolicy(ctx context.Context, in *SetPolicyRequest, opts ...grpc.CallOption) (*Policy, error) {
	out := new(Policy)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/SetPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*Policy, error) {
	out := new(Policy)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/GetPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) CreateOnboarding(ctx context.Context, in *CreateOnboardingRequest, opts ...grpc.CallOption) (*CreateOnboardingResponse, error) {
	out := new(CreateOnboardingResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.AccountAPI/CreateOnboarding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAPIServer is the server API for AccountAPI service.
type AccountAPIServer interface {
	// List the Spaces that are children of given parent.
	ListSpaces(context.Context, *ListSpacesRequest) (*ListSpacesResponse, error)
	// Retrieve specified space by name.
	GetSpace(context.Context, *GetSpaceRequest) (*Space, error)
	// Create a new Space to contain resources.
	CreateSpace(context.Context, *CreateSpaceRequest) (*Space, error)
	// Update configuration of a Space.
	UpdateSpace(context.Context, *UpdateSpaceRequest) (*Space, error)
	// Permanently destroy a Space.
	DeleteSpace(context.Context, *DeleteSpaceRequest) (*Space, error)
	// SetPolicy for permissions in a Space.
	SetPolicy(context.Context, *SetPolicyRequest) (*Policy, error)
	// GetPolicy for permissions in a Space.
	GetPolicy(context.Context, *GetPolicyRequest) (*Policy, error)
	// CreateOnboarding notifies a user to initiate their onboarding to a Space.
	CreateOnboarding(context.Context, *CreateOnboardingRequest) (*CreateOnboardingResponse, error)
}

// UnimplementedAccountAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAccountAPIServer struct {
}

func (*UnimplementedAccountAPIServer) ListSpaces(ctx context.Context, req *ListSpacesRequest) (*ListSpacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSpaces not implemented")
}
func (*UnimplementedAccountAPIServer) GetSpace(ctx context.Context, req *GetSpaceRequest) (*Space, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpace not implemented")
}
func (*UnimplementedAccountAPIServer) CreateSpace(ctx context.Context, req *CreateSpaceRequest) (*Space, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSpace not implemented")
}
func (*UnimplementedAccountAPIServer) UpdateSpace(ctx context.Context, req *UpdateSpaceRequest) (*Space, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpace not implemented")
}
func (*UnimplementedAccountAPIServer) DeleteSpace(ctx context.Context, req *DeleteSpaceRequest) (*Space, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSpace not implemented")
}
func (*UnimplementedAccountAPIServer) SetPolicy(ctx context.Context, req *SetPolicyRequest) (*Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPolicy not implemented")
}
func (*UnimplementedAccountAPIServer) GetPolicy(ctx context.Context, req *GetPolicyRequest) (*Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicy not implemented")
}
func (*UnimplementedAccountAPIServer) CreateOnboarding(ctx context.Context, req *CreateOnboardingRequest) (*CreateOnboardingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOnboarding not implemented")
}

func RegisterAccountAPIServer(s *grpc.Server, srv AccountAPIServer) {
	s.RegisterService(&_AccountAPI_serviceDesc, srv)
}

func _AccountAPI_ListSpaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).ListSpaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/ListSpaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).ListSpaces(ctx, req.(*ListSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/GetSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetSpace(ctx, req.(*GetSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_CreateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).CreateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/CreateSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).CreateSpace(ctx, req.(*CreateSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_UpdateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).UpdateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/UpdateSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).UpdateSpace(ctx, req.(*UpdateSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_DeleteSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).DeleteSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/DeleteSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).DeleteSpace(ctx, req.(*DeleteSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_SetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).SetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/SetPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).SetPolicy(ctx, req.(*SetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/GetPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_CreateOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).CreateOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.AccountAPI/CreateOnboarding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).CreateOnboarding(ctx, req.(*CreateOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "indent.v1.AccountAPI",
	HandlerType: (*AccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpaces",
			Handler:    _AccountAPI_ListSpaces_Handler,
		},
		{
			MethodName: "GetSpace",
			Handler:    _AccountAPI_GetSpace_Handler,
		},
		{
			MethodName: "CreateSpace",
			Handler:    _AccountAPI_CreateSpace_Handler,
		},
		{
			MethodName: "UpdateSpace",
			Handler:    _AccountAPI_UpdateSpace_Handler,
		},
		{
			MethodName: "DeleteSpace",
			Handler:    _AccountAPI_DeleteSpace_Handler,
		},
		{
			MethodName: "SetPolicy",
			Handler:    _AccountAPI_SetPolicy_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _AccountAPI_GetPolicy_Handler,
		},
		{
			MethodName: "CreateOnboarding",
			Handler:    _AccountAPI_CreateOnboarding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indent/v1/account_api.proto",
}
