// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indent/v1/config_api.proto

package indentv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigID struct {
	// ExternalID is the unique identifier for the provider instance.
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// SpaceName is where the config resides.
	SpaceName            string   `protobuf:"bytes,5,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigID) Reset()         { *m = ConfigID{} }
func (m *ConfigID) String() string { return proto.CompactTextString(m) }
func (*ConfigID) ProtoMessage()    {}
func (*ConfigID) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe172f7c177d6b5, []int{0}
}

func (m *ConfigID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigID.Unmarshal(m, b)
}
func (m *ConfigID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigID.Marshal(b, m, deterministic)
}
func (m *ConfigID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigID.Merge(m, src)
}
func (m *ConfigID) XXX_Size() int {
	return xxx_messageInfo_ConfigID.Size(m)
}
func (m *ConfigID) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigID.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigID proto.InternalMessageInfo

func (m *ConfigID) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *ConfigID) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func init() {
	proto.RegisterType((*ConfigID)(nil), "indent.v1.ConfigID")
}

func init() {
	proto.RegisterFile("indent/v1/config_api.proto", fileDescriptor_6fe172f7c177d6b5)
}

var fileDescriptor_6fe172f7c177d6b5 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xca, 0xcc, 0x4b, 0x49,
	0xcd, 0x2b, 0xd1, 0x2f, 0x33, 0xd4, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x8f, 0x4f, 0x2c, 0xc8,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xc8, 0xe9, 0x95, 0x19, 0x2a, 0x79, 0x71,
	0x71, 0x38, 0x83, 0xa5, 0x3d, 0x5d, 0x84, 0xe4, 0xb9, 0xb8, 0x53, 0x2b, 0x4a, 0x52, 0x8b, 0xf2,
	0x12, 0x73, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xb8, 0x60, 0x42, 0x9e,
	0x29, 0x42, 0xb2, 0x5c, 0x5c, 0xc5, 0x05, 0x89, 0xc9, 0xa9, 0xf1, 0x79, 0x89, 0xb9, 0xa9, 0x12,
	0xac, 0x60, 0x79, 0x4e, 0xb0, 0x88, 0x5f, 0x62, 0x6e, 0xaa, 0x53, 0x00, 0x17, 0x6f, 0x72, 0x7e,
	0xae, 0x1e, 0xdc, 0x70, 0x27, 0x6e, 0x88, 0xd1, 0x01, 0x20, 0x4b, 0x03, 0x18, 0xa3, 0x84, 0xe0,
	0x4e, 0xb2, 0x86, 0xb0, 0xca, 0x0c, 0x17, 0x31, 0x31, 0x7b, 0x46, 0x44, 0xac, 0x62, 0xe2, 0xf4,
	0x84, 0x68, 0x0a, 0x33, 0x3c, 0x05, 0x63, 0xc7, 0x84, 0x19, 0x26, 0xb1, 0x81, 0xdd, 0x6b, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x39, 0x32, 0x0b, 0xce, 0xcd, 0x00, 0x00, 0x00,
}
