// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indent/v1/install_api.proto

package indentv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "go.indent.com/indent-go/api/indent/audit/v1"
	_ "go.indent.com/indent-go/api/indent/log"
	_ "go.indent.com/indent-go/api/indent/sql"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Failure struct {
	// Meta contains metadata about the Failure.
	Meta *v1.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Status is the response status returned from an Integration failure.
	Status *status.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// RelatedEvents contain all events that occurred leading up to the Failure event.
	RelatedEvents []*v1.Event `protobuf:"bytes,5,rep,name=related_events,json=relatedEvents,proto3" json:"related_events,omitempty"`
	// Install that failed.
	Install              *Install `protobuf:"bytes,7,opt,name=install,proto3" json:"install,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Failure) Reset()         { *m = Failure{} }
func (m *Failure) String() string { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()    {}
func (*Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{0}
}

func (m *Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failure.Unmarshal(m, b)
}
func (m *Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failure.Marshal(b, m, deterministic)
}
func (m *Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failure.Merge(m, src)
}
func (m *Failure) XXX_Size() int {
	return xxx_messageInfo_Failure.Size(m)
}
func (m *Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_Failure proto.InternalMessageInfo

func (m *Failure) GetMeta() *v1.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Failure) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Failure) GetRelatedEvents() []*v1.Event {
	if m != nil {
		return m.RelatedEvents
	}
	return nil
}

func (m *Failure) GetInstall() *Install {
	if m != nil {
		return m.Install
	}
	return nil
}

type CreateFailureRequest struct {
	// Name of space containing Failure.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Failure is the event created from an Integration failure.
	Failure              *Failure `protobuf:"bytes,5,opt,name=failure,proto3" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFailureRequest) Reset()         { *m = CreateFailureRequest{} }
func (m *CreateFailureRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFailureRequest) ProtoMessage()    {}
func (*CreateFailureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{1}
}

func (m *CreateFailureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFailureRequest.Unmarshal(m, b)
}
func (m *CreateFailureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFailureRequest.Marshal(b, m, deterministic)
}
func (m *CreateFailureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFailureRequest.Merge(m, src)
}
func (m *CreateFailureRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFailureRequest.Size(m)
}
func (m *CreateFailureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFailureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFailureRequest proto.InternalMessageInfo

func (m *CreateFailureRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *CreateFailureRequest) GetFailure() *Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

type GetFailureRequest struct {
	// Name of space containing Failure.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of the Failure.
	FailureName          string   `protobuf:"bytes,5,opt,name=failure_name,json=failureName,proto3" json:"failure_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFailureRequest) Reset()         { *m = GetFailureRequest{} }
func (m *GetFailureRequest) String() string { return proto.CompactTextString(m) }
func (*GetFailureRequest) ProtoMessage()    {}
func (*GetFailureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{2}
}

func (m *GetFailureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFailureRequest.Unmarshal(m, b)
}
func (m *GetFailureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFailureRequest.Marshal(b, m, deterministic)
}
func (m *GetFailureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFailureRequest.Merge(m, src)
}
func (m *GetFailureRequest) XXX_Size() int {
	return xxx_messageInfo_GetFailureRequest.Size(m)
}
func (m *GetFailureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFailureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFailureRequest proto.InternalMessageInfo

func (m *GetFailureRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *GetFailureRequest) GetFailureName() string {
	if m != nil {
		return m.FailureName
	}
	return ""
}

type ListFailuresRequest struct {
	// Name of space containing Failures.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Integration name related to the Failures.
	IntegrationName string `protobuf:"bytes,3,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	// Install name related to the Failures.
	InstallName string `protobuf:"bytes,4,opt,name=install_name,json=installName,proto3" json:"install_name,omitempty"`
	// Max number of Failures to be returned.
	PageSize int32 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for current page position for this list of Failures.
	PageToken            string   `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFailuresRequest) Reset()         { *m = ListFailuresRequest{} }
func (m *ListFailuresRequest) String() string { return proto.CompactTextString(m) }
func (*ListFailuresRequest) ProtoMessage()    {}
func (*ListFailuresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{3}
}

func (m *ListFailuresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFailuresRequest.Unmarshal(m, b)
}
func (m *ListFailuresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFailuresRequest.Marshal(b, m, deterministic)
}
func (m *ListFailuresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFailuresRequest.Merge(m, src)
}
func (m *ListFailuresRequest) XXX_Size() int {
	return xxx_messageInfo_ListFailuresRequest.Size(m)
}
func (m *ListFailuresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFailuresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFailuresRequest proto.InternalMessageInfo

func (m *ListFailuresRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *ListFailuresRequest) GetIntegrationName() string {
	if m != nil {
		return m.IntegrationName
	}
	return ""
}

func (m *ListFailuresRequest) GetInstallName() string {
	if m != nil {
		return m.InstallName
	}
	return ""
}

func (m *ListFailuresRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListFailuresRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListFailuresResponse struct {
	// Paginated list of sanitized Failures in a Space.
	Failures []*Failure `protobuf:"bytes,1,rep,name=failures,proto3" json:"failures,omitempty"`
	// Page cursor for list of Failures.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFailuresResponse) Reset()         { *m = ListFailuresResponse{} }
func (m *ListFailuresResponse) String() string { return proto.CompactTextString(m) }
func (*ListFailuresResponse) ProtoMessage()    {}
func (*ListFailuresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{4}
}

func (m *ListFailuresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFailuresResponse.Unmarshal(m, b)
}
func (m *ListFailuresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFailuresResponse.Marshal(b, m, deterministic)
}
func (m *ListFailuresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFailuresResponse.Merge(m, src)
}
func (m *ListFailuresResponse) XXX_Size() int {
	return xxx_messageInfo_ListFailuresResponse.Size(m)
}
func (m *ListFailuresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFailuresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFailuresResponse proto.InternalMessageInfo

func (m *ListFailuresResponse) GetFailures() []*Failure {
	if m != nil {
		return m.Failures
	}
	return nil
}

func (m *ListFailuresResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type Install struct {
	// Meta contains metadata about the Install.
	Meta *v1.Meta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	// Integration that is setup by the Install.
	IntegrationName string `protobuf:"bytes,5,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	// Capabilities of the Install.
	Capabilities *Capabilities `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Disabled specifies when the Install shouldn't be used.
	Disabled bool `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	//  // User-facing string explaining status (ex: status.Failed: `couldn't read credentials`)
	//  google.rpc.Status status_explanation = 13;
	// Status of the install and its current place in the lifecycle: Created, SetupFailed, Active, Disabled, ActionRequired, Failed, Generated
	Status string `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	// LastSuccess stores the last time the Install successfully did a read/write action
	LastSuccess *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	// TenantId stores the ID used to identify the tenant (slack team id, google workspace id, ...)
	TenantId string `protobuf:"bytes,19,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// CredentialName stores the reference to the credential used to auth with an integration
	CredentialName string `protobuf:"bytes,21,opt,name=credential_name,json=credentialName,proto3" json:"credential_name,omitempty"`
	// LEGACY: Integration that is setup by the Install.
	Integration          *Integration `protobuf:"bytes,99,opt,name=integration,proto3" json:"integration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Install) Reset()         { *m = Install{} }
func (m *Install) String() string { return proto.CompactTextString(m) }
func (*Install) ProtoMessage()    {}
func (*Install) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{5}
}

func (m *Install) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install.Unmarshal(m, b)
}
func (m *Install) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install.Marshal(b, m, deterministic)
}
func (m *Install) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install.Merge(m, src)
}
func (m *Install) XXX_Size() int {
	return xxx_messageInfo_Install.Size(m)
}
func (m *Install) XXX_DiscardUnknown() {
	xxx_messageInfo_Install.DiscardUnknown(m)
}

var xxx_messageInfo_Install proto.InternalMessageInfo

func (m *Install) GetMeta() *v1.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Install) GetIntegrationName() string {
	if m != nil {
		return m.IntegrationName
	}
	return ""
}

func (m *Install) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *Install) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *Install) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Install) GetLastSuccess() *timestamppb.Timestamp {
	if m != nil {
		return m.LastSuccess
	}
	return nil
}

func (m *Install) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *Install) GetCredentialName() string {
	if m != nil {
		return m.CredentialName
	}
	return ""
}

func (m *Install) GetIntegration() *Integration {
	if m != nil {
		return m.Integration
	}
	return nil
}

type ListInstallsRequest struct {
	// Name of space containing Installs.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// LabelSelector specifies which Installs should be returned.
	LabelSelector string `protobuf:"bytes,2,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	// Kinds that must be supported by the Installs.
	Kinds []string `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// Capabilities that must be supported by the Installs.
	Capabilities []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Max number of Installs to be returned.
	PageSize int32 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for current page position for this list of Installs.
	PageToken            string   `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListInstallsRequest) Reset()         { *m = ListInstallsRequest{} }
func (m *ListInstallsRequest) String() string { return proto.CompactTextString(m) }
func (*ListInstallsRequest) ProtoMessage()    {}
func (*ListInstallsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{6}
}

func (m *ListInstallsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInstallsRequest.Unmarshal(m, b)
}
func (m *ListInstallsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInstallsRequest.Marshal(b, m, deterministic)
}
func (m *ListInstallsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInstallsRequest.Merge(m, src)
}
func (m *ListInstallsRequest) XXX_Size() int {
	return xxx_messageInfo_ListInstallsRequest.Size(m)
}
func (m *ListInstallsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInstallsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListInstallsRequest proto.InternalMessageInfo

func (m *ListInstallsRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *ListInstallsRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *ListInstallsRequest) GetKinds() []string {
	if m != nil {
		return m.Kinds
	}
	return nil
}

func (m *ListInstallsRequest) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *ListInstallsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListInstallsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListInstallsResponse struct {
	// Paginated list of Installs in a Space.
	Installs []*Install `protobuf:"bytes,1,rep,name=installs,proto3" json:"installs,omitempty"`
	// Page cursor for list of Installs.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListInstallsResponse) Reset()         { *m = ListInstallsResponse{} }
func (m *ListInstallsResponse) String() string { return proto.CompactTextString(m) }
func (*ListInstallsResponse) ProtoMessage()    {}
func (*ListInstallsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{7}
}

func (m *ListInstallsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInstallsResponse.Unmarshal(m, b)
}
func (m *ListInstallsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInstallsResponse.Marshal(b, m, deterministic)
}
func (m *ListInstallsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInstallsResponse.Merge(m, src)
}
func (m *ListInstallsResponse) XXX_Size() int {
	return xxx_messageInfo_ListInstallsResponse.Size(m)
}
func (m *ListInstallsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInstallsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListInstallsResponse proto.InternalMessageInfo

func (m *ListInstallsResponse) GetInstalls() []*Install {
	if m != nil {
		return m.Installs
	}
	return nil
}

func (m *ListInstallsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetInstallRequest struct {
	// Name of space containing Install.
	SpaceName string `protobuf:"bytes,5,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of the Install.
	InstallName          string   `protobuf:"bytes,9,opt,name=install_name,json=installName,proto3" json:"install_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstallRequest) Reset()         { *m = GetInstallRequest{} }
func (m *GetInstallRequest) String() string { return proto.CompactTextString(m) }
func (*GetInstallRequest) ProtoMessage()    {}
func (*GetInstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{8}
}

func (m *GetInstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstallRequest.Unmarshal(m, b)
}
func (m *GetInstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstallRequest.Marshal(b, m, deterministic)
}
func (m *GetInstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstallRequest.Merge(m, src)
}
func (m *GetInstallRequest) XXX_Size() int {
	return xxx_messageInfo_GetInstallRequest.Size(m)
}
func (m *GetInstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstallRequest proto.InternalMessageInfo

func (m *GetInstallRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *GetInstallRequest) GetInstallName() string {
	if m != nil {
		return m.InstallName
	}
	return ""
}

// Defines an Install to be created.
type CreateInstallRequest struct {
	// Name of space containing Install.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Install being created
	Install              *Install `protobuf:"bytes,2,opt,name=install,proto3" json:"install,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateInstallRequest) Reset()         { *m = CreateInstallRequest{} }
func (m *CreateInstallRequest) String() string { return proto.CompactTextString(m) }
func (*CreateInstallRequest) ProtoMessage()    {}
func (*CreateInstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{9}
}

func (m *CreateInstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInstallRequest.Unmarshal(m, b)
}
func (m *CreateInstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInstallRequest.Marshal(b, m, deterministic)
}
func (m *CreateInstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInstallRequest.Merge(m, src)
}
func (m *CreateInstallRequest) XXX_Size() int {
	return xxx_messageInfo_CreateInstallRequest.Size(m)
}
func (m *CreateInstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInstallRequest proto.InternalMessageInfo

func (m *CreateInstallRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *CreateInstallRequest) GetInstall() *Install {
	if m != nil {
		return m.Install
	}
	return nil
}

// Defines an Install to be updated.
type UpdateInstallRequest struct {
	// Name of space containing Install.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of the Install.
	InstallName string `protobuf:"bytes,2,opt,name=install_name,json=installName,proto3" json:"install_name,omitempty"`
	// Install with changes to be implemented.
	Install              *Install `protobuf:"bytes,3,opt,name=install,proto3" json:"install,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInstallRequest) Reset()         { *m = UpdateInstallRequest{} }
func (m *UpdateInstallRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInstallRequest) ProtoMessage()    {}
func (*UpdateInstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{10}
}

func (m *UpdateInstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInstallRequest.Unmarshal(m, b)
}
func (m *UpdateInstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInstallRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInstallRequest.Merge(m, src)
}
func (m *UpdateInstallRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInstallRequest.Size(m)
}
func (m *UpdateInstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInstallRequest proto.InternalMessageInfo

func (m *UpdateInstallRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *UpdateInstallRequest) GetInstallName() string {
	if m != nil {
		return m.InstallName
	}
	return ""
}

func (m *UpdateInstallRequest) GetInstall() *Install {
	if m != nil {
		return m.Install
	}
	return nil
}

// Defines an Install to be toggled.
type ToggleInstallRequest struct {
	// Name of space containing Install.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of the Install.
	InstallName          string   `protobuf:"bytes,2,opt,name=install_name,json=installName,proto3" json:"install_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleInstallRequest) Reset()         { *m = ToggleInstallRequest{} }
func (m *ToggleInstallRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleInstallRequest) ProtoMessage()    {}
func (*ToggleInstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{11}
}

func (m *ToggleInstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleInstallRequest.Unmarshal(m, b)
}
func (m *ToggleInstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleInstallRequest.Marshal(b, m, deterministic)
}
func (m *ToggleInstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleInstallRequest.Merge(m, src)
}
func (m *ToggleInstallRequest) XXX_Size() int {
	return xxx_messageInfo_ToggleInstallRequest.Size(m)
}
func (m *ToggleInstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleInstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleInstallRequest proto.InternalMessageInfo

func (m *ToggleInstallRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *ToggleInstallRequest) GetInstallName() string {
	if m != nil {
		return m.InstallName
	}
	return ""
}

// Defines an Install to be deleted.
type DeleteInstallRequest struct {
	// Name of space containing Install.
	SpaceName string `protobuf:"bytes,5,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of the Install.
	InstallName          string   `protobuf:"bytes,9,opt,name=install_name,json=installName,proto3" json:"install_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInstallRequest) Reset()         { *m = DeleteInstallRequest{} }
func (m *DeleteInstallRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteInstallRequest) ProtoMessage()    {}
func (*DeleteInstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{12}
}

func (m *DeleteInstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstallRequest.Unmarshal(m, b)
}
func (m *DeleteInstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstallRequest.Marshal(b, m, deterministic)
}
func (m *DeleteInstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstallRequest.Merge(m, src)
}
func (m *DeleteInstallRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteInstallRequest.Size(m)
}
func (m *DeleteInstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstallRequest proto.InternalMessageInfo

func (m *DeleteInstallRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *DeleteInstallRequest) GetInstallName() string {
	if m != nil {
		return m.InstallName
	}
	return ""
}

type GetInstallSetupRequest struct {
	// Name of space for install.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of install
	InstallName          string   `protobuf:"bytes,3,opt,name=install_name,json=installName,proto3" json:"install_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstallSetupRequest) Reset()         { *m = GetInstallSetupRequest{} }
func (m *GetInstallSetupRequest) String() string { return proto.CompactTextString(m) }
func (*GetInstallSetupRequest) ProtoMessage()    {}
func (*GetInstallSetupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{13}
}

func (m *GetInstallSetupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstallSetupRequest.Unmarshal(m, b)
}
func (m *GetInstallSetupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstallSetupRequest.Marshal(b, m, deterministic)
}
func (m *GetInstallSetupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstallSetupRequest.Merge(m, src)
}
func (m *GetInstallSetupRequest) XXX_Size() int {
	return xxx_messageInfo_GetInstallSetupRequest.Size(m)
}
func (m *GetInstallSetupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstallSetupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstallSetupRequest proto.InternalMessageInfo

func (m *GetInstallSetupRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *GetInstallSetupRequest) GetInstallName() string {
	if m != nil {
		return m.InstallName
	}
	return ""
}

type UpdateInstallSetupRequest struct {
	// Name of space for install.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of install
	InstallName string `protobuf:"bytes,3,opt,name=install_name,json=installName,proto3" json:"install_name,omitempty"`
	// Form containing setup information for the setup of an integration
	Form                 *Form    `protobuf:"bytes,5,opt,name=form,proto3" json:"form,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInstallSetupRequest) Reset()         { *m = UpdateInstallSetupRequest{} }
func (m *UpdateInstallSetupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInstallSetupRequest) ProtoMessage()    {}
func (*UpdateInstallSetupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{14}
}

func (m *UpdateInstallSetupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInstallSetupRequest.Unmarshal(m, b)
}
func (m *UpdateInstallSetupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInstallSetupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInstallSetupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInstallSetupRequest.Merge(m, src)
}
func (m *UpdateInstallSetupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInstallSetupRequest.Size(m)
}
func (m *UpdateInstallSetupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInstallSetupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInstallSetupRequest proto.InternalMessageInfo

func (m *UpdateInstallSetupRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *UpdateInstallSetupRequest) GetInstallName() string {
	if m != nil {
		return m.InstallName
	}
	return ""
}

func (m *UpdateInstallSetupRequest) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

type GetInstallSetupResponse struct {
	// Form containing setup information for the setup of an integration
	Form                 *Form    `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstallSetupResponse) Reset()         { *m = GetInstallSetupResponse{} }
func (m *GetInstallSetupResponse) String() string { return proto.CompactTextString(m) }
func (*GetInstallSetupResponse) ProtoMessage()    {}
func (*GetInstallSetupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{15}
}

func (m *GetInstallSetupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstallSetupResponse.Unmarshal(m, b)
}
func (m *GetInstallSetupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstallSetupResponse.Marshal(b, m, deterministic)
}
func (m *GetInstallSetupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstallSetupResponse.Merge(m, src)
}
func (m *GetInstallSetupResponse) XXX_Size() int {
	return xxx_messageInfo_GetInstallSetupResponse.Size(m)
}
func (m *GetInstallSetupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstallSetupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstallSetupResponse proto.InternalMessageInfo

func (m *GetInstallSetupResponse) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

type UpdateInstallSetupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInstallSetupResponse) Reset()         { *m = UpdateInstallSetupResponse{} }
func (m *UpdateInstallSetupResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateInstallSetupResponse) ProtoMessage()    {}
func (*UpdateInstallSetupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71c7e44ca1d1b2a1, []int{16}
}

func (m *UpdateInstallSetupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInstallSetupResponse.Unmarshal(m, b)
}
func (m *UpdateInstallSetupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInstallSetupResponse.Marshal(b, m, deterministic)
}
func (m *UpdateInstallSetupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInstallSetupResponse.Merge(m, src)
}
func (m *UpdateInstallSetupResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateInstallSetupResponse.Size(m)
}
func (m *UpdateInstallSetupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInstallSetupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInstallSetupResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Failure)(nil), "indent.v1.Failure")
	proto.RegisterType((*CreateFailureRequest)(nil), "indent.v1.CreateFailureRequest")
	proto.RegisterType((*GetFailureRequest)(nil), "indent.v1.GetFailureRequest")
	proto.RegisterType((*ListFailuresRequest)(nil), "indent.v1.ListFailuresRequest")
	proto.RegisterType((*ListFailuresResponse)(nil), "indent.v1.ListFailuresResponse")
	proto.RegisterType((*Install)(nil), "indent.v1.Install")
	proto.RegisterType((*ListInstallsRequest)(nil), "indent.v1.ListInstallsRequest")
	proto.RegisterType((*ListInstallsResponse)(nil), "indent.v1.ListInstallsResponse")
	proto.RegisterType((*GetInstallRequest)(nil), "indent.v1.GetInstallRequest")
	proto.RegisterType((*CreateInstallRequest)(nil), "indent.v1.CreateInstallRequest")
	proto.RegisterType((*UpdateInstallRequest)(nil), "indent.v1.UpdateInstallRequest")
	proto.RegisterType((*ToggleInstallRequest)(nil), "indent.v1.ToggleInstallRequest")
	proto.RegisterType((*DeleteInstallRequest)(nil), "indent.v1.DeleteInstallRequest")
	proto.RegisterType((*GetInstallSetupRequest)(nil), "indent.v1.GetInstallSetupRequest")
	proto.RegisterType((*UpdateInstallSetupRequest)(nil), "indent.v1.UpdateInstallSetupRequest")
	proto.RegisterType((*GetInstallSetupResponse)(nil), "indent.v1.GetInstallSetupResponse")
	proto.RegisterType((*UpdateInstallSetupResponse)(nil), "indent.v1.UpdateInstallSetupResponse")
}

func init() {
	proto.RegisterFile("indent/v1/install_api.proto", fileDescriptor_71c7e44ca1d1b2a1)
}

var fileDescriptor_71c7e44ca1d1b2a1 = []byte{
	// 1348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcf, 0x6f, 0x1b, 0xc5,
	0x17, 0xd7, 0xc6, 0x71, 0x13, 0xbf, 0xc4, 0xf1, 0xb7, 0xd3, 0x34, 0xdd, 0xba, 0xf9, 0x62, 0x77,
	0xcb, 0x8f, 0x94, 0x16, 0x6f, 0x1d, 0x04, 0x2d, 0xa9, 0x5a, 0x20, 0x69, 0x41, 0xa9, 0xa0, 0x44,
	0x4e, 0x5a, 0x55, 0x08, 0x69, 0x35, 0x59, 0x4f, 0xac, 0x55, 0xd7, 0xbb, 0xdb, 0x9d, 0x71, 0x4a,
	0x5b, 0xf5, 0x00, 0x42, 0x5c, 0x90, 0x38, 0xc0, 0x01, 0x89, 0x23, 0x07, 0x0e, 0xfc, 0x17, 0x41,
	0x88, 0x03, 0x57, 0x2e, 0x70, 0xe7, 0x02, 0x7f, 0x42, 0x4f, 0x68, 0x67, 0x67, 0xbc, 0xb3, 0x3f,
	0x5c, 0xd7, 0x44, 0x8d, 0x64, 0xc9, 0x7e, 0xef, 0xcd, 0x7c, 0x3e, 0xef, 0xed, 0xfb, 0xbc, 0x99,
	0x0d, 0x9c, 0x72, 0xbc, 0x2e, 0xf1, 0x98, 0xb9, 0xdf, 0x36, 0x1d, 0x8f, 0x32, 0xec, 0xba, 0x16,
	0x0e, 0x9c, 0x56, 0x10, 0xfa, 0xcc, 0x47, 0x95, 0xd8, 0xd9, 0xda, 0x6f, 0xd7, 0x97, 0x7b, 0xbe,
	0xdf, 0x73, 0x89, 0x89, 0x03, 0xc7, 0xc4, 0x9e, 0xe7, 0x33, 0xcc, 0x1c, 0xdf, 0xa3, 0x71, 0x60,
	0xfd, 0x94, 0xf0, 0xf2, 0x5f, 0xbb, 0x83, 0x3d, 0x93, 0xf4, 0x03, 0xf6, 0x40, 0x38, 0x97, 0xb3,
	0x4e, 0xca, 0xc2, 0x81, 0xcd, 0x84, 0xb7, 0x91, 0xf5, 0x32, 0xa7, 0x4f, 0x28, 0xc3, 0xfd, 0x40,
	0x04, 0x9c, 0x10, 0x01, 0x61, 0x60, 0x9b, 0x94, 0x61, 0x36, 0x90, 0xa0, 0x0d, 0x41, 0x1d, 0x0f,
	0xba, 0x0e, 0x4f, 0x20, 0x24, 0xd4, 0x1f, 0x84, 0x36, 0xc9, 0x06, 0xf0, 0xdc, 0x18, 0xe9, 0x85,
	0x9c, 0x73, 0x92, 0x5f, 0x7d, 0x51, 0x04, 0xb8, 0x7e, 0x2f, 0xfa, 0x64, 0xac, 0xf4, 0x9e, 0x1b,
	0x7d, 0x84, 0xf5, 0x64, 0xb2, 0x59, 0x06, 0xc7, 0xf8, 0x53, 0x83, 0x99, 0xf7, 0xb0, 0xe3, 0x0e,
	0x42, 0x82, 0xce, 0xc2, 0x74, 0x9f, 0x30, 0xac, 0x6b, 0x4d, 0x6d, 0x65, 0x6e, 0xf5, 0x78, 0x4b,
	0x54, 0x90, 0x73, 0x6c, 0xed, 0xb7, 0x5b, 0x1f, 0x12, 0x86, 0x3b, 0x3c, 0x04, 0x5d, 0x80, 0x23,
	0x71, 0x3e, 0x7a, 0x89, 0x07, 0xa3, 0x56, 0x9c, 0x69, 0x2b, 0x0c, 0xec, 0xd6, 0x36, 0xf7, 0xac,
	0x4f, 0xff, 0xf1, 0x73, 0x43, 0xeb, 0x88, 0x38, 0x74, 0x05, 0x16, 0x42, 0xe2, 0x62, 0x46, 0xba,
	0x16, 0xd9, 0x27, 0x1e, 0xa3, 0x7a, 0xb9, 0x59, 0x5a, 0x99, 0x5b, 0x5d, 0xca, 0xc1, 0x5c, 0x8f,
	0xdc, 0x9d, 0xaa, 0x88, 0xe6, 0xbf, 0x28, 0x5a, 0x85, 0x19, 0xf1, 0x8c, 0xf5, 0x19, 0x81, 0x38,
	0x7c, 0xc0, 0xad, 0xcd, 0xd8, 0x23, 0x10, 0x65, 0xa0, 0x61, 0xc3, 0xe2, 0x46, 0x48, 0x30, 0x23,
	0x22, 0xc1, 0x0e, 0xb9, 0x37, 0x20, 0x94, 0xa1, 0xff, 0x03, 0xd0, 0x00, 0xdb, 0xc4, 0xf2, 0x70,
	0x9f, 0xf0, 0x6c, 0x2b, 0x9d, 0x0a, 0xb7, 0xdc, 0xc4, 0x7d, 0x82, 0xce, 0xc3, 0xcc, 0x5e, 0xbc,
	0x40, 0x2f, 0xe7, 0xa0, 0xe4, 0x56, 0x32, 0xc4, 0xb8, 0x05, 0x47, 0xdf, 0x27, 0x6c, 0x32, 0x84,
	0xd3, 0x30, 0x2f, 0x96, 0xc7, 0x01, 0x65, 0x1e, 0x30, 0x27, 0x6c, 0x51, 0x88, 0xf1, 0x8b, 0x06,
	0xc7, 0x3e, 0x70, 0xa8, 0xdc, 0x98, 0xca, 0x9d, 0xcf, 0xe4, 0x77, 0x16, 0x69, 0x2b, 0xfb, 0x9f,
	0x85, 0xff, 0xa9, 0x4d, 0xc3, 0x43, 0x4b, 0x1c, 0xa3, 0xa6, 0xd8, 0x25, 0x15, 0xa9, 0x1d, 0x1e,
	0x36, 0x1d, 0x53, 0x11, 0x36, 0x1e, 0x72, 0x0a, 0x2a, 0x01, 0xee, 0x11, 0x8b, 0x3a, 0x0f, 0x89,
	0x0e, 0x4d, 0x6d, 0xa5, 0xdc, 0x99, 0x8d, 0x0c, 0xdb, 0xce, 0x43, 0x12, 0x65, 0xca, 0x9d, 0xcc,
	0xbf, 0x4b, 0x3c, 0x7d, 0x2e, 0xce, 0x34, 0xb2, 0xec, 0x44, 0x06, 0xc3, 0x83, 0xc5, 0x74, 0x16,
	0x34, 0xf0, 0x3d, 0x4a, 0x50, 0x0b, 0x66, 0x45, 0xb6, 0x54, 0xd7, 0x78, 0x1f, 0x14, 0x15, 0x79,
	0x18, 0x83, 0x5e, 0x86, 0x9a, 0x47, 0x3e, 0x65, 0x96, 0x82, 0x35, 0xc5, 0xb1, 0xaa, 0x91, 0x79,
	0x6b, 0x88, 0xf7, 0xd5, 0x34, 0xcc, 0x88, 0x6e, 0x40, 0xa6, 0x68, 0xe7, 0xd2, 0x53, 0xda, 0x59,
	0xd4, 0x2e, 0x6e, 0x6a, 0xb3, 0xa0, 0x6c, 0x65, 0xa5, 0xc2, 0xb9, 0xe2, 0xdd, 0x80, 0x79, 0x1b,
	0x07, 0x78, 0xd7, 0x71, 0x1d, 0xe6, 0x10, 0x2a, 0x3a, 0xf3, 0x84, 0x92, 0xc9, 0x86, 0xe2, 0x5e,
	0xaf, 0x7e, 0x7f, 0xd0, 0x28, 0xdf, 0xd8, 0xfe, 0xe8, 0xe6, 0x3a, 0xdf, 0x2e, 0xb5, 0x16, 0x35,
	0x61, 0xb6, 0xeb, 0x50, 0xbc, 0xeb, 0x92, 0xae, 0x5e, 0x69, 0x6a, 0x2b, 0xb3, 0x02, 0x74, 0x68,
	0x45, 0xcb, 0x43, 0xcd, 0xd5, 0x14, 0x52, 0x52, 0x5f, 0x1b, 0x30, 0xef, 0x62, 0xca, 0x2c, 0x3a,
	0xb0, 0x6d, 0x42, 0xa9, 0x7e, 0x94, 0x73, 0xa9, 0x4b, 0x5d, 0xca, 0x11, 0xd5, 0xda, 0x91, 0x23,
	0x4a, 0xac, 0x9f, 0x8b, 0x56, 0x6d, 0xc7, 0x8b, 0xd0, 0x69, 0xa8, 0x30, 0xe2, 0x61, 0x8f, 0x59,
	0x4e, 0x57, 0x3f, 0xa6, 0xa0, 0xcc, 0xc6, 0xe6, 0xcd, 0x2e, 0x7a, 0x0d, 0x6a, 0x76, 0x48, 0xa2,
	0xfc, 0x1c, 0x2c, 0x7a, 0xe6, 0xb8, 0x12, 0xb8, 0x90, 0x38, 0x79, 0x89, 0xae, 0xc2, 0x9c, 0x52,
	0x35, 0xdd, 0xe6, 0xac, 0x96, 0x52, 0xda, 0x1d, 0x7a, 0x25, 0x23, 0x65, 0xc1, 0xda, 0xe5, 0x7f,
	0x0e, 0x1a, 0xcb, 0x17, 0xa2, 0xbf, 0x4b, 0x96, 0xcd, 0xc5, 0x6c, 0x89, 0xde, 0xa4, 0x16, 0x8b,
	0xea, 0xf2, 0xe4, 0xa0, 0x01, 0xd1, 0xd3, 0xb3, 0x78, 0xfb, 0x3f, 0x39, 0x68, 0x54, 0xf8, 0xaf,
	0x88, 0x98, 0xf1, 0xb7, 0x10, 0x91, 0xe8, 0x88, 0xc9, 0x44, 0x74, 0x0e, 0x16, 0x5c, 0xbc, 0x4b,
	0x5c, 0x8b, 0x12, 0x97, 0xd8, 0xcc, 0x0f, 0xe3, 0x8e, 0x13, 0x81, 0x55, 0xee, 0xdb, 0x16, 0x2e,
	0x54, 0x87, 0xf2, 0x5d, 0xc7, 0xeb, 0x52, 0x7d, 0xba, 0x59, 0x1a, 0xc6, 0xc4, 0x26, 0xb4, 0x92,
	0xeb, 0x92, 0x24, 0x24, 0xdd, 0x03, 0x87, 0x51, 0x1a, 0x8b, 0x95, 0x96, 0xa4, 0x9a, 0x28, 0x4d,
	0x16, 0xac, 0x40, 0x69, 0x22, 0xbc, 0x33, 0x8c, 0x41, 0xe7, 0x47, 0x28, 0x4d, 0xe6, 0x9d, 0xd6,
	0x1b, 0xe6, 0xd3, 0x4f, 0xee, 0x52, 0x58, 0xde, 0x72, 0x71, 0x79, 0x5f, 0xc9, 0x0c, 0x9e, 0x8a,
	0x12, 0xa6, 0x8e, 0x9f, 0x64, 0x8a, 0x67, 0x50, 0xc6, 0x4f, 0x71, 0x79, 0x60, 0x4c, 0x8d, 0x3a,
	0x30, 0x92, 0xa3, 0xe2, 0x1b, 0x0d, 0x16, 0x6f, 0x05, 0xdd, 0x3c, 0xca, 0x33, 0xb5, 0x4a, 0x36,
	0x97, 0xa9, 0x11, 0xb9, 0xa8, 0xa4, 0x4a, 0xe3, 0x49, 0x75, 0x61, 0x71, 0xc7, 0xef, 0xf5, 0xdc,
	0xe7, 0xca, 0x29, 0x42, 0xb9, 0x46, 0x5c, 0x32, 0x26, 0xf3, 0xc3, 0x3e, 0xc5, 0x3d, 0x58, 0x4a,
	0x1a, 0x65, 0x9b, 0xb0, 0x41, 0x70, 0xa8, 0x6c, 0x4a, 0xa3, 0x70, 0xbe, 0xd6, 0xe0, 0x64, 0xea,
	0x41, 0x3e, 0x3f, 0x2c, 0x74, 0x06, 0xa6, 0xf7, 0xfc, 0xb0, 0x2f, 0x6e, 0x09, 0x35, 0xf5, 0x00,
	0xf3, 0xc3, 0x7e, 0x87, 0x3b, 0x8d, 0xab, 0x70, 0x22, 0x97, 0xb8, 0x90, 0xa6, 0x5c, 0xaf, 0x3d,
	0x6d, 0xfd, 0x32, 0xd4, 0x8b, 0xf2, 0x89, 0xb7, 0x58, 0xfd, 0x75, 0x1e, 0x40, 0x38, 0xde, 0xdd,
	0xda, 0x44, 0x0f, 0x60, 0x5e, 0x1d, 0x02, 0xe8, 0x05, 0x65, 0xcf, 0x82, 0x41, 0x58, 0x6f, 0x8c,
	0xf4, 0xc7, 0xfb, 0x1b, 0x2b, 0x9f, 0xff, 0xfe, 0xd7, 0xb7, 0x53, 0x06, 0x6a, 0x46, 0x77, 0x47,
	0x5e, 0x22, 0x6a, 0x3e, 0x4a, 0x4a, 0xf8, 0xd8, 0x1c, 0xce, 0x8d, 0xfb, 0x00, 0x49, 0x9e, 0x68,
	0x59, 0xd9, 0x38, 0x37, 0x20, 0xea, 0x05, 0x5d, 0x6f, 0x5c, 0xe4, 0x48, 0x6d, 0x64, 0x8e, 0x43,
	0x32, 0x1f, 0xa9, 0x4f, 0xe7, 0x31, 0xba, 0x0f, 0xd5, 0xd4, 0x7c, 0x40, 0x6a, 0x52, 0x45, 0x93,
	0xa3, 0x10, 0xbe, 0xcd, 0xe1, 0xcf, 0x19, 0x63, 0x13, 0x5d, 0x93, 0xf2, 0x44, 0x5f, 0x6a, 0x50,
	0x4d, 0x3d, 0x9a, 0x14, 0x72, 0xd1, 0x34, 0x29, 0x44, 0x7e, 0x87, 0x23, 0xaf, 0x19, 0x93, 0x26,
	0x9e, 0x10, 0xf9, 0x42, 0x83, 0xea, 0x75, 0x2f, 0x3a, 0x0c, 0x8b, 0x88, 0x14, 0x8d, 0x90, 0x42,
	0x22, 0x57, 0x39, 0x91, 0x4b, 0xc6, 0x9b, 0x93, 0x12, 0x21, 0x1c, 0x3b, 0xaa, 0xc7, 0xc2, 0xb5,
	0xf8, 0xb2, 0x72, 0x28, 0x1e, 0x6f, 0x73, 0x1e, 0x6f, 0x19, 0x17, 0x27, 0xe5, 0x21, 0x6e, 0x4a,
	0xe8, 0x33, 0x0d, 0xaa, 0xa9, 0x91, 0x96, 0xe2, 0x51, 0x34, 0xec, 0xea, 0x4b, 0xb9, 0x7b, 0xd2,
	0xf5, 0xe8, 0x2d, 0x50, 0x76, 0xe5, 0xab, 0x13, 0x77, 0xa5, 0x50, 0xa2, 0xbc, 0xf8, 0xe6, 0x94,
	0x98, 0xb9, 0xd7, 0xe7, 0x94, 0x98, 0xbd, 0x31, 0x8f, 0x57, 0xe2, 0xf0, 0xae, 0x1c, 0x2b, 0x51,
	0xbe, 0xd4, 0x65, 0x94, 0x98, 0x7e, 0x51, 0xa9, 0x17, 0xdc, 0xba, 0xc7, 0x2b, 0x51, 0x22, 0x99,
	0x8f, 0xd4, 0xb7, 0x18, 0x45, 0x89, 0x12, 0x3b, 0xaf, 0xc4, 0x67, 0x80, 0x1f, 0xab, 0x44, 0x09,
	0xbf, 0x26, 0xdf, 0xc1, 0xd0, 0x77, 0x1a, 0xd4, 0x32, 0x43, 0x16, 0x9d, 0x2e, 0x9c, 0x40, 0xea,
	0x69, 0x50, 0x37, 0x9e, 0x16, 0x22, 0xca, 0x7e, 0x85, 0xb3, 0xb9, 0x88, 0xde, 0x98, 0xb0, 0x01,
	0x4c, 0xca, 0x59, 0xfc, 0xa8, 0x01, 0xca, 0x8f, 0x6f, 0xf4, 0xe2, 0xa8, 0x41, 0x91, 0xe2, 0xf7,
	0xd2, 0x98, 0x28, 0x41, 0x71, 0x83, 0x53, 0xbc, 0x62, 0xfc, 0x37, 0x8a, 0x6b, 0xfc, 0x98, 0x59,
	0xdf, 0x81, 0xaa, 0xed, 0xf7, 0x13, 0xc0, 0xf5, 0x9a, 0x3c, 0x56, 0x02, 0x67, 0x2b, 0xd2, 0xc4,
	0x96, 0xf6, 0x31, 0x1a, 0xfe, 0x1b, 0xe1, 0x72, 0xfc, 0x6d, 0xbf, 0xfd, 0xc3, 0x54, 0x69, 0xf3,
	0xce, 0x9d, 0x9f, 0xa6, 0x2a, 0x9b, 0xf1, 0xc2, 0xdb, 0xed, 0xdf, 0xe4, 0xf7, 0x4f, 0x6e, 0xb7,
	0x77, 0x8f, 0x70, 0x39, 0xbd, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xff, 0x14, 0xd9,
	0xaa, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InstallAPIClient is the client API for InstallAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstallAPIClient interface {
	// List Installs that have been added to the space.
	ListInstalls(ctx context.Context, in *ListInstallsRequest, opts ...grpc.CallOption) (*ListInstallsResponse, error)
	// Retrieve specified Install by name and space.
	GetInstall(ctx context.Context, in *GetInstallRequest, opts ...grpc.CallOption) (*Install, error)
	// Create a new Install in given Space.
	CreateInstall(ctx context.Context, in *CreateInstallRequest, opts ...grpc.CallOption) (*Install, error)
	// Update an Install in given Space.
	UpdateInstall(ctx context.Context, in *UpdateInstallRequest, opts ...grpc.CallOption) (*Install, error)
	// Enable an Install.
	EnableInstall(ctx context.Context, in *ToggleInstallRequest, opts ...grpc.CallOption) (*Install, error)
	// Disable an Install.
	DisableInstall(ctx context.Context, in *ToggleInstallRequest, opts ...grpc.CallOption) (*Install, error)
	// Delete an Install.
	DeleteInstall(ctx context.Context, in *DeleteInstallRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List Failures.
	ListFailures(ctx context.Context, in *ListFailuresRequest, opts ...grpc.CallOption) (*ListFailuresResponse, error)
	// Retrieve specified Failure by name and space.
	GetFailure(ctx context.Context, in *GetFailureRequest, opts ...grpc.CallOption) (*Failure, error)
	// Create Failure.
	CreateFailure(ctx context.Context, in *CreateFailureRequest, opts ...grpc.CallOption) (*Failure, error)
	// Retrieve an install's integration's Setup form.
	GetInstallSetup(ctx context.Context, in *GetInstallSetupRequest, opts ...grpc.CallOption) (*GetInstallSetupResponse, error)
	// Post an install's Setup form.
	UpdateInstallSetup(ctx context.Context, in *UpdateInstallSetupRequest, opts ...grpc.CallOption) (*UpdateInstallSetupResponse, error)
}

type installAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInstallAPIClient(cc grpc.ClientConnInterface) InstallAPIClient {
	return &installAPIClient{cc}
}

func (c *installAPIClient) ListInstalls(ctx context.Context, in *ListInstallsRequest, opts ...grpc.CallOption) (*ListInstallsResponse, error) {
	out := new(ListInstallsResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/ListInstalls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) GetInstall(ctx context.Context, in *GetInstallRequest, opts ...grpc.CallOption) (*Install, error) {
	out := new(Install)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/GetInstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) CreateInstall(ctx context.Context, in *CreateInstallRequest, opts ...grpc.CallOption) (*Install, error) {
	out := new(Install)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/CreateInstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) UpdateInstall(ctx context.Context, in *UpdateInstallRequest, opts ...grpc.CallOption) (*Install, error) {
	out := new(Install)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/UpdateInstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) EnableInstall(ctx context.Context, in *ToggleInstallRequest, opts ...grpc.CallOption) (*Install, error) {
	out := new(Install)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/EnableInstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) DisableInstall(ctx context.Context, in *ToggleInstallRequest, opts ...grpc.CallOption) (*Install, error) {
	out := new(Install)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/DisableInstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) DeleteInstall(ctx context.Context, in *DeleteInstallRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/DeleteInstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) ListFailures(ctx context.Context, in *ListFailuresRequest, opts ...grpc.CallOption) (*ListFailuresResponse, error) {
	out := new(ListFailuresResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/ListFailures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) GetFailure(ctx context.Context, in *GetFailureRequest, opts ...grpc.CallOption) (*Failure, error) {
	out := new(Failure)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/GetFailure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) CreateFailure(ctx context.Context, in *CreateFailureRequest, opts ...grpc.CallOption) (*Failure, error) {
	out := new(Failure)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/CreateFailure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) GetInstallSetup(ctx context.Context, in *GetInstallSetupRequest, opts ...grpc.CallOption) (*GetInstallSetupResponse, error) {
	out := new(GetInstallSetupResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/GetInstallSetup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installAPIClient) UpdateInstallSetup(ctx context.Context, in *UpdateInstallSetupRequest, opts ...grpc.CallOption) (*UpdateInstallSetupResponse, error) {
	out := new(UpdateInstallSetupResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.InstallAPI/UpdateInstallSetup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstallAPIServer is the server API for InstallAPI service.
type InstallAPIServer interface {
	// List Installs that have been added to the space.
	ListInstalls(context.Context, *ListInstallsRequest) (*ListInstallsResponse, error)
	// Retrieve specified Install by name and space.
	GetInstall(context.Context, *GetInstallRequest) (*Install, error)
	// Create a new Install in given Space.
	CreateInstall(context.Context, *CreateInstallRequest) (*Install, error)
	// Update an Install in given Space.
	UpdateInstall(context.Context, *UpdateInstallRequest) (*Install, error)
	// Enable an Install.
	EnableInstall(context.Context, *ToggleInstallRequest) (*Install, error)
	// Disable an Install.
	DisableInstall(context.Context, *ToggleInstallRequest) (*Install, error)
	// Delete an Install.
	DeleteInstall(context.Context, *DeleteInstallRequest) (*emptypb.Empty, error)
	// List Failures.
	ListFailures(context.Context, *ListFailuresRequest) (*ListFailuresResponse, error)
	// Retrieve specified Failure by name and space.
	GetFailure(context.Context, *GetFailureRequest) (*Failure, error)
	// Create Failure.
	CreateFailure(context.Context, *CreateFailureRequest) (*Failure, error)
	// Retrieve an install's integration's Setup form.
	GetInstallSetup(context.Context, *GetInstallSetupRequest) (*GetInstallSetupResponse, error)
	// Post an install's Setup form.
	UpdateInstallSetup(context.Context, *UpdateInstallSetupRequest) (*UpdateInstallSetupResponse, error)
}

// UnimplementedInstallAPIServer can be embedded to have forward compatible implementations.
type UnimplementedInstallAPIServer struct {
}

func (*UnimplementedInstallAPIServer) ListInstalls(ctx context.Context, req *ListInstallsRequest) (*ListInstallsResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method ListInstalls not implemented")
}
func (*UnimplementedInstallAPIServer) GetInstall(ctx context.Context, req *GetInstallRequest) (*Install, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method GetInstall not implemented")
}
func (*UnimplementedInstallAPIServer) CreateInstall(ctx context.Context, req *CreateInstallRequest) (*Install, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method CreateInstall not implemented")
}
func (*UnimplementedInstallAPIServer) UpdateInstall(ctx context.Context, req *UpdateInstallRequest) (*Install, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method UpdateInstall not implemented")
}
func (*UnimplementedInstallAPIServer) EnableInstall(ctx context.Context, req *ToggleInstallRequest) (*Install, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method EnableInstall not implemented")
}
func (*UnimplementedInstallAPIServer) DisableInstall(ctx context.Context, req *ToggleInstallRequest) (*Install, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method DisableInstall not implemented")
}
func (*UnimplementedInstallAPIServer) DeleteInstall(ctx context.Context, req *DeleteInstallRequest) (*emptypb.Empty, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method DeleteInstall not implemented")
}
func (*UnimplementedInstallAPIServer) ListFailures(ctx context.Context, req *ListFailuresRequest) (*ListFailuresResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method ListFailures not implemented")
}
func (*UnimplementedInstallAPIServer) GetFailure(ctx context.Context, req *GetFailureRequest) (*Failure, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method GetFailure not implemented")
}
func (*UnimplementedInstallAPIServer) CreateFailure(ctx context.Context, req *CreateFailureRequest) (*Failure, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method CreateFailure not implemented")
}
func (*UnimplementedInstallAPIServer) GetInstallSetup(ctx context.Context, req *GetInstallSetupRequest) (*GetInstallSetupResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method GetInstallSetup not implemented")
}
func (*UnimplementedInstallAPIServer) UpdateInstallSetup(ctx context.Context, req *UpdateInstallSetupRequest) (*UpdateInstallSetupResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method UpdateInstallSetup not implemented")
}

func RegisterInstallAPIServer(s *grpc.Server, srv InstallAPIServer) {
	s.RegisterService(&_InstallAPI_serviceDesc, srv)
}

func _InstallAPI_ListInstalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).ListInstalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/ListInstalls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).ListInstalls(ctx, req.(*ListInstallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_GetInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).GetInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/GetInstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).GetInstall(ctx, req.(*GetInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_CreateInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).CreateInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/CreateInstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).CreateInstall(ctx, req.(*CreateInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_UpdateInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).UpdateInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/UpdateInstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).UpdateInstall(ctx, req.(*UpdateInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_EnableInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).EnableInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/EnableInstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).EnableInstall(ctx, req.(*ToggleInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_DisableInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).DisableInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/DisableInstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).DisableInstall(ctx, req.(*ToggleInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_DeleteInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).DeleteInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/DeleteInstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).DeleteInstall(ctx, req.(*DeleteInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_ListFailures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFailuresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).ListFailures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/ListFailures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).ListFailures(ctx, req.(*ListFailuresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_GetFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).GetFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/GetFailure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).GetFailure(ctx, req.(*GetFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_CreateFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).CreateFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/CreateFailure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).CreateFailure(ctx, req.(*CreateFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_GetInstallSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).GetInstallSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/GetInstallSetup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).GetInstallSetup(ctx, req.(*GetInstallSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallAPI_UpdateInstallSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstallSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallAPIServer).UpdateInstallSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.InstallAPI/UpdateInstallSetup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallAPIServer).UpdateInstallSetup(ctx, req.(*UpdateInstallSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InstallAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "indent.v1.InstallAPI",
	HandlerType: (*InstallAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstalls",
			Handler:    _InstallAPI_ListInstalls_Handler,
		},
		{
			MethodName: "GetInstall",
			Handler:    _InstallAPI_GetInstall_Handler,
		},
		{
			MethodName: "CreateInstall",
			Handler:    _InstallAPI_CreateInstall_Handler,
		},
		{
			MethodName: "UpdateInstall",
			Handler:    _InstallAPI_UpdateInstall_Handler,
		},
		{
			MethodName: "EnableInstall",
			Handler:    _InstallAPI_EnableInstall_Handler,
		},
		{
			MethodName: "DisableInstall",
			Handler:    _InstallAPI_DisableInstall_Handler,
		},
		{
			MethodName: "DeleteInstall",
			Handler:    _InstallAPI_DeleteInstall_Handler,
		},
		{
			MethodName: "ListFailures",
			Handler:    _InstallAPI_ListFailures_Handler,
		},
		{
			MethodName: "GetFailure",
			Handler:    _InstallAPI_GetFailure_Handler,
		},
		{
			MethodName: "CreateFailure",
			Handler:    _InstallAPI_CreateFailure_Handler,
		},
		{
			MethodName: "GetInstallSetup",
			Handler:    _InstallAPI_GetInstallSetup_Handler,
		},
		{
			MethodName: "UpdateInstallSetup",
			Handler:    _InstallAPI_UpdateInstallSetup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indent/v1/install_api.proto",
}
