// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indent/v1/integration_api.proto

package indentv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "go.indent.com/indent-go/api/indent/audit/v1"
	_ "go.indent.com/indent-go/api/indent/log"
	_ "go.indent.com/indent-go/api/indent/sql"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupVersionKind struct {
	// Group of Kinds being represented.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Version of the Group.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Kind of resource being represented,
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupVersionKind) Reset()         { *m = GroupVersionKind{} }
func (m *GroupVersionKind) String() string { return proto.CompactTextString(m) }
func (*GroupVersionKind) ProtoMessage()    {}
func (*GroupVersionKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_d466beb30e81ebe2, []int{0}
}

func (m *GroupVersionKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupVersionKind.Unmarshal(m, b)
}
func (m *GroupVersionKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupVersionKind.Marshal(b, m, deterministic)
}
func (m *GroupVersionKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupVersionKind.Merge(m, src)
}
func (m *GroupVersionKind) XXX_Size() int {
	return xxx_messageInfo_GroupVersionKind.Size(m)
}
func (m *GroupVersionKind) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupVersionKind.DiscardUnknown(m)
}

var xxx_messageInfo_GroupVersionKind proto.InternalMessageInfo

func (m *GroupVersionKind) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GroupVersionKind) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GroupVersionKind) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type Capabilities struct {
	// Kinds that are supported.
	Kinds []*GroupVersionKind `protobuf:"bytes,6,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// Capabilities that are supported.
	Capabilities         []string `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Capabilities) Reset()         { *m = Capabilities{} }
func (m *Capabilities) String() string { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()    {}
func (*Capabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_d466beb30e81ebe2, []int{1}
}

func (m *Capabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities.Unmarshal(m, b)
}
func (m *Capabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities.Marshal(b, m, deterministic)
}
func (m *Capabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities.Merge(m, src)
}
func (m *Capabilities) XXX_Size() int {
	return xxx_messageInfo_Capabilities.Size(m)
}
func (m *Capabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities proto.InternalMessageInfo

func (m *Capabilities) GetKinds() []*GroupVersionKind {
	if m != nil {
		return m.Kinds
	}
	return nil
}

func (m *Capabilities) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type Integration struct {
	// Meta contains metadata about the Integration.
	Meta *v1.Meta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	// Capabilities of the Integration.
	Capabilities         *Capabilities `protobuf:"bytes,9,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Integration) Reset()         { *m = Integration{} }
func (m *Integration) String() string { return proto.CompactTextString(m) }
func (*Integration) ProtoMessage()    {}
func (*Integration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d466beb30e81ebe2, []int{2}
}

func (m *Integration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integration.Unmarshal(m, b)
}
func (m *Integration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integration.Marshal(b, m, deterministic)
}
func (m *Integration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integration.Merge(m, src)
}
func (m *Integration) XXX_Size() int {
	return xxx_messageInfo_Integration.Size(m)
}
func (m *Integration) XXX_DiscardUnknown() {
	xxx_messageInfo_Integration.DiscardUnknown(m)
}

var xxx_messageInfo_Integration proto.InternalMessageInfo

func (m *Integration) GetMeta() *v1.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Integration) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type ListIntegrationsRequest struct {
	// Name of space containing Integration.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// LabelSelector specifies which Integrations should be returned.
	LabelSelector string `protobuf:"bytes,2,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	// Kinds that must be supported by the Integrations.
	Kinds []string `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// Capabilities that must be supported by the Integrations.
	Capabilities []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Max number of Integrations to be returned.
	PageSize int32 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for current page position for this list of Integrations.
	PageToken            string   `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIntegrationsRequest) Reset()         { *m = ListIntegrationsRequest{} }
func (m *ListIntegrationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListIntegrationsRequest) ProtoMessage()    {}
func (*ListIntegrationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d466beb30e81ebe2, []int{3}
}

func (m *ListIntegrationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIntegrationsRequest.Unmarshal(m, b)
}
func (m *ListIntegrationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIntegrationsRequest.Marshal(b, m, deterministic)
}
func (m *ListIntegrationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIntegrationsRequest.Merge(m, src)
}
func (m *ListIntegrationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListIntegrationsRequest.Size(m)
}
func (m *ListIntegrationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIntegrationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIntegrationsRequest proto.InternalMessageInfo

func (m *ListIntegrationsRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *ListIntegrationsRequest) GetLabelSelector() string {
	if m != nil {
		return m.LabelSelector
	}
	return ""
}

func (m *ListIntegrationsRequest) GetKinds() []string {
	if m != nil {
		return m.Kinds
	}
	return nil
}

func (m *ListIntegrationsRequest) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *ListIntegrationsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListIntegrationsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListIntegrationsResponse struct {
	// Paginated list of Integrations in a Space.
	Integrations []*Integration `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
	// Page cursor for list of Integrations.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIntegrationsResponse) Reset()         { *m = ListIntegrationsResponse{} }
func (m *ListIntegrationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListIntegrationsResponse) ProtoMessage()    {}
func (*ListIntegrationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d466beb30e81ebe2, []int{4}
}

func (m *ListIntegrationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIntegrationsResponse.Unmarshal(m, b)
}
func (m *ListIntegrationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIntegrationsResponse.Marshal(b, m, deterministic)
}
func (m *ListIntegrationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIntegrationsResponse.Merge(m, src)
}
func (m *ListIntegrationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListIntegrationsResponse.Size(m)
}
func (m *ListIntegrationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIntegrationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIntegrationsResponse proto.InternalMessageInfo

func (m *ListIntegrationsResponse) GetIntegrations() []*Integration {
	if m != nil {
		return m.Integrations
	}
	return nil
}

func (m *ListIntegrationsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetIntegrationRequest struct {
	// Name of space containing Integration.
	SpaceName string `protobuf:"bytes,5,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of the Integration.
	IntegrationName      string   `protobuf:"bytes,9,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIntegrationRequest) Reset()         { *m = GetIntegrationRequest{} }
func (m *GetIntegrationRequest) String() string { return proto.CompactTextString(m) }
func (*GetIntegrationRequest) ProtoMessage()    {}
func (*GetIntegrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d466beb30e81ebe2, []int{5}
}

func (m *GetIntegrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIntegrationRequest.Unmarshal(m, b)
}
func (m *GetIntegrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIntegrationRequest.Marshal(b, m, deterministic)
}
func (m *GetIntegrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIntegrationRequest.Merge(m, src)
}
func (m *GetIntegrationRequest) XXX_Size() int {
	return xxx_messageInfo_GetIntegrationRequest.Size(m)
}
func (m *GetIntegrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIntegrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIntegrationRequest proto.InternalMessageInfo

func (m *GetIntegrationRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *GetIntegrationRequest) GetIntegrationName() string {
	if m != nil {
		return m.IntegrationName
	}
	return ""
}

func init() {
	proto.RegisterType((*GroupVersionKind)(nil), "indent.v1.GroupVersionKind")
	proto.RegisterType((*Capabilities)(nil), "indent.v1.Capabilities")
	proto.RegisterType((*Integration)(nil), "indent.v1.Integration")
	proto.RegisterType((*ListIntegrationsRequest)(nil), "indent.v1.ListIntegrationsRequest")
	proto.RegisterType((*ListIntegrationsResponse)(nil), "indent.v1.ListIntegrationsResponse")
	proto.RegisterType((*GetIntegrationRequest)(nil), "indent.v1.GetIntegrationRequest")
}

func init() {
	proto.RegisterFile("indent/v1/integration_api.proto", fileDescriptor_d466beb30e81ebe2)
}

var fileDescriptor_d466beb30e81ebe2 = []byte{
	// 665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x6b, 0x13, 0x41,
	0x1c, 0x65, 0xf3, 0xa7, 0x6d, 0x7e, 0xe9, 0x3f, 0x46, 0x6b, 0x97, 0x54, 0x4d, 0xd8, 0x4a, 0x09,
	0x28, 0x59, 0x52, 0x0f, 0x45, 0x3d, 0x88, 0x11, 0x29, 0xc1, 0x3f, 0x84, 0x54, 0x4a, 0x11, 0x21,
	0x4c, 0x92, 0x9f, 0x71, 0xe8, 0xee, 0xce, 0x76, 0x67, 0x12, 0xb4, 0xa5, 0x1e, 0x04, 0x0f, 0xe2,
	0xd1, 0x2f, 0x20, 0x1e, 0xfb, 0x2d, 0xf4, 0xe8, 0xd5, 0x8b, 0x1f, 0xc0, 0xab, 0xdf, 0x41, 0x66,
	0x36, 0x9b, 0x4e, 0xd2, 0x44, 0x3c, 0x2c, 0x4c, 0xde, 0x7b, 0x33, 0xef, 0xcd, 0x9b, 0xcc, 0x40,
	0x91, 0x05, 0x5d, 0x0c, 0xa4, 0x3b, 0xa8, 0xba, 0x2c, 0x90, 0xd8, 0x8b, 0xa8, 0x64, 0x3c, 0x68,
	0xd1, 0x90, 0x55, 0xc2, 0x88, 0x4b, 0x4e, 0x72, 0xb1, 0xa0, 0x32, 0xa8, 0x16, 0xae, 0xf6, 0x38,
	0xef, 0x79, 0xe8, 0xd2, 0x90, 0xb9, 0x34, 0x08, 0xb8, 0xd4, 0x5a, 0x11, 0x0b, 0x0b, 0x1b, 0x43,
	0x56, 0xff, 0x6a, 0xf7, 0x5f, 0xb9, 0xe8, 0x87, 0xf2, 0xed, 0x90, 0x2c, 0x4e, 0x92, 0x92, 0xf9,
	0x28, 0x24, 0xf5, 0xc3, 0xa1, 0x60, 0x7d, 0x28, 0x88, 0xc2, 0x8e, 0x2b, 0x24, 0x95, 0xfd, 0x64,
	0xd9, 0x24, 0x20, 0xed, 0x77, 0x99, 0x8e, 0x19, 0xa1, 0xe0, 0xfd, 0xa8, 0x83, 0x89, 0xe0, 0xf2,
	0x50, 0xe0, 0xf1, 0x9e, 0xfa, 0x26, 0x50, 0x71, 0xe4, 0xa9, 0x2f, 0x46, 0x9d, 0xd7, 0xb0, 0xba,
	0x1b, 0xf1, 0x7e, 0xb8, 0x8f, 0x91, 0x60, 0x3c, 0x78, 0xcc, 0x82, 0x2e, 0x29, 0x40, 0xb6, 0xa7,
	0x30, 0xdb, 0x2a, 0x59, 0xe5, 0x5c, 0x2d, 0xf3, 0xeb, 0x7b, 0xd1, 0x6a, 0xc6, 0x10, 0xb9, 0x0e,
	0xf3, 0x83, 0x58, 0x6a, 0xa7, 0x0c, 0x36, 0x01, 0x89, 0x0d, 0x99, 0x43, 0x16, 0x74, 0xed, 0xb4,
	0x41, 0x6a, 0xc4, 0x39, 0x82, 0xc5, 0x87, 0x34, 0xa4, 0x6d, 0xe6, 0x31, 0xc9, 0x50, 0x90, 0x1d,
	0xc8, 0x2a, 0x5c, 0xd8, 0x73, 0xa5, 0x74, 0x39, 0xbf, 0xbd, 0x51, 0x19, 0xd5, 0x5a, 0x99, 0x4c,
	0x94, 0x44, 0xd0, 0x7a, 0x52, 0x86, 0xc5, 0x8e, 0xb1, 0x90, 0x9d, 0x2b, 0xa5, 0x47, 0x56, 0x63,
	0x8c, 0xf3, 0xc1, 0x82, 0x7c, 0xfd, 0xfc, 0x0c, 0x89, 0x0b, 0x19, 0x1f, 0x25, 0xd5, 0xe1, 0xf2,
	0xdb, 0x6b, 0x89, 0xa3, 0x2e, 0x52, 0xf9, 0x3e, 0x45, 0x49, 0x93, 0xcc, 0x4a, 0x48, 0x1e, 0x5d,
	0xb0, 0x52, 0x13, 0xd7, 0x8d, 0xa8, 0xe6, 0x96, 0x6a, 0x0b, 0x5f, 0xbe, 0x15, 0xad, 0x29, 0x39,
	0xfe, 0x58, 0xb0, 0xfe, 0x84, 0x09, 0x69, 0x64, 0x11, 0x4d, 0x3c, 0xea, 0xa3, 0x90, 0x64, 0x13,
	0x40, 0x84, 0xb4, 0x83, 0xad, 0x80, 0xfa, 0x38, 0xd6, 0x78, 0x4e, 0xe3, 0xcf, 0xa8, 0x8f, 0xe4,
	0x26, 0x2c, 0x7b, 0xb4, 0x8d, 0x5e, 0x4b, 0xa0, 0x87, 0x1d, 0xc9, 0xa3, 0xb1, 0xf2, 0x97, 0x34,
	0xb7, 0x37, 0xa4, 0xd4, 0xf1, 0xc5, 0xc5, 0x66, 0x8c, 0x62, 0x66, 0x74, 0x37, 0x3f, 0xab, 0x3b,
	0xb2, 0x01, 0xb9, 0x90, 0xf6, 0xb0, 0x25, 0xd8, 0x31, 0xda, 0x50, 0xb2, 0xca, 0xd9, 0xe6, 0x82,
	0x02, 0xf6, 0xd8, 0x31, 0x92, 0x6b, 0x00, 0x9a, 0x94, 0xfc, 0x10, 0x03, 0x3b, 0xaf, 0xb2, 0x34,
	0xb5, 0xfc, 0xb9, 0x02, 0x9c, 0x77, 0x60, 0x5f, 0xdc, 0xae, 0x08, 0x79, 0x20, 0x90, 0xdc, 0x85,
	0x45, 0xe3, 0x5a, 0x09, 0xdb, 0xd2, 0xa7, 0x7f, 0xc5, 0xa8, 0xd4, 0x98, 0xd6, 0x1c, 0xd3, 0x92,
	0x2d, 0x58, 0x09, 0xf0, 0x8d, 0x6c, 0x19, 0xde, 0xba, 0x87, 0xe6, 0x92, 0x82, 0x1b, 0x23, 0x7f,
	0x1f, 0xd6, 0x76, 0xd1, 0xb4, 0x9f, 0x5e, 0x76, 0x76, 0x7a, 0xd9, 0x2e, 0xac, 0x9a, 0x17, 0x5f,
	0x4b, 0x73, 0x86, 0x74, 0xc5, 0x60, 0xd5, 0x84, 0xed, 0xb3, 0x14, 0x2c, 0x1b, 0x66, 0x0f, 0x1a,
	0x75, 0xf2, 0xd1, 0x82, 0xd5, 0xc9, 0x0a, 0x88, 0x63, 0x6c, 0x72, 0xc6, 0xdf, 0xa1, 0xb0, 0xf9,
	0x4f, 0x4d, 0xdc, 0xa1, 0x73, 0xeb, 0xfd, 0xcf, 0xdf, 0x9f, 0x53, 0x5b, 0xe4, 0x86, 0xba, 0xfd,
	0x3a, 0xb8, 0x70, 0x4f, 0xce, 0x37, 0x76, 0xea, 0x8e, 0xb5, 0xf6, 0xc9, 0x82, 0xe5, 0xf1, 0x3a,
	0x48, 0xc9, 0xbc, 0x6c, 0xd3, 0x9a, 0x2a, 0xcc, 0x38, 0x10, 0xe7, 0xbe, 0xb6, 0xbe, 0x43, 0x76,
	0xfe, 0xc7, 0xda, 0x3d, 0x99, 0x2c, 0xf2, 0xb4, 0x76, 0x00, 0x4b, 0x1d, 0xee, 0x9f, 0xaf, 0x5e,
	0xbb, 0x64, 0x56, 0x17, 0xb2, 0x86, 0x7a, 0x96, 0x1a, 0xd6, 0x0b, 0x32, 0x7a, 0x86, 0xef, 0xc5,
	0xa3, 0x41, 0xf5, 0x6b, 0x2a, 0x5d, 0x3f, 0x38, 0x38, 0x4b, 0xe5, 0xea, 0xf1, 0xe4, 0xfd, 0xea,
	0x8f, 0x64, 0xfc, 0x72, 0xbf, 0xda, 0x9e, 0xd3, 0x2f, 0xda, 0xed, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x29, 0x00, 0x14, 0xee, 0xc1, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IntegrationAPIClient is the client API for IntegrationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntegrationAPIClient interface {
	// List Integrations available to be installed.
	ListIntegrations(ctx context.Context, in *ListIntegrationsRequest, opts ...grpc.CallOption) (*ListIntegrationsResponse, error)
	// Retrieve specified Integration by name and space.
	GetIntegration(ctx context.Context, in *GetIntegrationRequest, opts ...grpc.CallOption) (*Integration, error)
}

type integrationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationAPIClient(cc grpc.ClientConnInterface) IntegrationAPIClient {
	return &integrationAPIClient{cc}
}

func (c *integrationAPIClient) ListIntegrations(ctx context.Context, in *ListIntegrationsRequest, opts ...grpc.CallOption) (*ListIntegrationsResponse, error) {
	out := new(ListIntegrationsResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.IntegrationAPI/ListIntegrations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationAPIClient) GetIntegration(ctx context.Context, in *GetIntegrationRequest, opts ...grpc.CallOption) (*Integration, error) {
	out := new(Integration)
	err := c.cc.Invoke(ctx, "/indent.v1.IntegrationAPI/GetIntegration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationAPIServer is the server API for IntegrationAPI service.
type IntegrationAPIServer interface {
	// List Integrations available to be installed.
	ListIntegrations(context.Context, *ListIntegrationsRequest) (*ListIntegrationsResponse, error)
	// Retrieve specified Integration by name and space.
	GetIntegration(context.Context, *GetIntegrationRequest) (*Integration, error)
}

// UnimplementedIntegrationAPIServer can be embedded to have forward compatible implementations.
type UnimplementedIntegrationAPIServer struct {
}

func (*UnimplementedIntegrationAPIServer) ListIntegrations(ctx context.Context, req *ListIntegrationsRequest) (*ListIntegrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntegrations not implemented")
}
func (*UnimplementedIntegrationAPIServer) GetIntegration(ctx context.Context, req *GetIntegrationRequest) (*Integration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegration not implemented")
}

func RegisterIntegrationAPIServer(s *grpc.Server, srv IntegrationAPIServer) {
	s.RegisterService(&_IntegrationAPI_serviceDesc, srv)
}

func _IntegrationAPI_ListIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntegrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationAPIServer).ListIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.IntegrationAPI/ListIntegrations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationAPIServer).ListIntegrations(ctx, req.(*ListIntegrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationAPI_GetIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationAPIServer).GetIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.IntegrationAPI/GetIntegration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationAPIServer).GetIntegration(ctx, req.(*GetIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IntegrationAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "indent.v1.IntegrationAPI",
	HandlerType: (*IntegrationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIntegrations",
			Handler:    _IntegrationAPI_ListIntegrations_Handler,
		},
		{
			MethodName: "GetIntegration",
			Handler:    _IntegrationAPI_GetIntegration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indent/v1/integration_api.proto",
}
