// Code generated by protoc-gen-zap-marshaler. DO NOT EDIT.
// Generated conservatively: no ObjectMarshaler implementations for messages
// without any logged fields.

package indentv1

import (
	zapcore "go.uber.org/zap/zapcore"
)

func (m *Block) MarshalLogObject(oe zapcore.ObjectEncoder) error {
	var keyName string
	_ = keyName

	if m == nil {
		return nil
	}

	keyName = "Name" // field name = 1
	oe.AddString(keyName, m.Name)

	keyName = "SpaceName" // field spaceName = 2
	oe.AddString(keyName, m.SpaceName)

	keyName = "DisplayName" // field displayName = 3
	oe.AddString(keyName, m.DisplayName)

	return nil
}
