// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indent/v1/task_api.proto

package indentv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "go.indent.com/indent-go/api/indent/audit/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Phase of the Task.
type Task_Phase int32

const (
	Task_UNKNOWN Task_Phase = 0
	Task_OPEN    Task_Phase = 1
	Task_CLOSED  Task_Phase = 2
	Task_DONE    Task_Phase = 3
)

var Task_Phase_name = map[int32]string{
	0: "UNKNOWN",
	1: "OPEN",
	2: "CLOSED",
	3: "DONE",
}

var Task_Phase_value = map[string]int32{
	"UNKNOWN": 0,
	"OPEN":    1,
	"CLOSED":  2,
	"DONE":    3,
}

func (x Task_Phase) String() string {
	return proto.EnumName(Task_Phase_name, int32(x))
}

func (Task_Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{7, 0}
}

type ListTasksRequest struct {
	// Space of Tasks to retrieve.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Max number of Tasks to be returned.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Among constrains listed tasks by name.
	Among                []string `protobuf:"bytes,4,rep,name=among,proto3" json:"among,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksRequest) Reset()         { *m = ListTasksRequest{} }
func (m *ListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*ListTasksRequest) ProtoMessage()    {}
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{0}
}

func (m *ListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksRequest.Unmarshal(m, b)
}
func (m *ListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksRequest.Marshal(b, m, deterministic)
}
func (m *ListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksRequest.Merge(m, src)
}
func (m *ListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_ListTasksRequest.Size(m)
}
func (m *ListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksRequest proto.InternalMessageInfo

func (m *ListTasksRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *ListTasksRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListTasksRequest) GetAmong() []string {
	if m != nil {
		return m.Among
	}
	return nil
}

type ListTasksResponse struct {
	// Paginated list of Tasks that are children of the parent resource.
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksResponse) Reset()         { *m = ListTasksResponse{} }
func (m *ListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*ListTasksResponse) ProtoMessage()    {}
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{1}
}

func (m *ListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResponse.Unmarshal(m, b)
}
func (m *ListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResponse.Marshal(b, m, deterministic)
}
func (m *ListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResponse.Merge(m, src)
}
func (m *ListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_ListTasksResponse.Size(m)
}
func (m *ListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResponse proto.InternalMessageInfo

func (m *ListTasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type GetTaskRequest struct {
	// Space of Task to retrieve.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of Task.
	TaskName             string   `protobuf:"bytes,5,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{2}
}

func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(m, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *GetTaskRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

type CreateTaskRequest struct {
	// Space to create Task in;
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Task being created.
	Task                 *Task    `protobuf:"bytes,5,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{3}
}

func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (m *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(m, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *CreateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	// Resource name of Task to update.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of Task.
	TaskName string `protobuf:"bytes,5,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// Task with changes to be implemented.
	Task                 *Task    `protobuf:"bytes,10,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{4}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *UpdateTaskRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *UpdateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	// Name of the Task to be deleted.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Name of Task.
	TaskName             string   `protobuf:"bytes,5,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{5}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *DeleteTaskRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

// Details about a Petition on a Task
type TaskPetitionDetails struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	PetitionID           string   `protobuf:"bytes,2,opt,name=petitionID,proto3" json:"petitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskPetitionDetails) Reset()         { *m = TaskPetitionDetails{} }
func (m *TaskPetitionDetails) String() string { return proto.CompactTextString(m) }
func (*TaskPetitionDetails) ProtoMessage()    {}
func (*TaskPetitionDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{6}
}

func (m *TaskPetitionDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskPetitionDetails.Unmarshal(m, b)
}
func (m *TaskPetitionDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskPetitionDetails.Marshal(b, m, deterministic)
}
func (m *TaskPetitionDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskPetitionDetails.Merge(m, src)
}
func (m *TaskPetitionDetails) XXX_Size() int {
	return xxx_messageInfo_TaskPetitionDetails.Size(m)
}
func (m *TaskPetitionDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskPetitionDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TaskPetitionDetails proto.InternalMessageInfo

func (m *TaskPetitionDetails) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *TaskPetitionDetails) GetPetitionID() string {
	if m != nil {
		return m.PetitionID
	}
	return ""
}

// Task in a Organization's hierarchy.
type Task struct {
	// Resource name of a Task.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Name of Space of Task.
	SpaceName string `protobuf:"bytes,5,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Meta contains generic information about the Task.
	Meta *v1.Meta `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	// Text that should be shown to users to represent a Task.
	DisplayName string `protobuf:"bytes,20,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Description provides a short summary of the Task and what's necessary to complete it.
	Description string `protobuf:"bytes,25,opt,name=description,proto3" json:"description,omitempty"`
	// Assignee is responsible for completing the Task.
	Assignee *v1.Resource `protobuf:"bytes,30,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Phase    Task_Phase   `protobuf:"varint,35,opt,name=phase,proto3,enum=indent.v1.Task_Phase" json:"phase,omitempty"`
	// Form data associated with a Task.
	Form *Form `protobuf:"bytes,40,opt,name=form,proto3" json:"form,omitempty"`
	// Details about the scope of a Task.
	//
	// Types that are valid to be assigned to Details:
	//	*Task_PetitionDetails
	Details              isTask_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_947671edfa2a898b, []int{7}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

func (m *Task) GetMeta() *v1.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Task) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetAssignee() *v1.Resource {
	if m != nil {
		return m.Assignee
	}
	return nil
}

func (m *Task) GetPhase() Task_Phase {
	if m != nil {
		return m.Phase
	}
	return Task_UNKNOWN
}

func (m *Task) GetForm() *Form {
	if m != nil {
		return m.Form
	}
	return nil
}

type isTask_Details interface {
	isTask_Details()
}

type Task_PetitionDetails struct {
	PetitionDetails *TaskPetitionDetails `protobuf:"bytes,45,opt,name=petition_details,json=petitionDetails,proto3,oneof"`
}

func (*Task_PetitionDetails) isTask_Details() {}

func (m *Task) GetDetails() isTask_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Task) GetPetitionDetails() *TaskPetitionDetails {
	if x, ok := m.GetDetails().(*Task_PetitionDetails); ok {
		return x.PetitionDetails
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Task) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Task_PetitionDetails)(nil),
	}
}

func init() {
	proto.RegisterEnum("indent.v1.Task_Phase", Task_Phase_name, Task_Phase_value)
	proto.RegisterType((*ListTasksRequest)(nil), "indent.v1.ListTasksRequest")
	proto.RegisterType((*ListTasksResponse)(nil), "indent.v1.ListTasksResponse")
	proto.RegisterType((*GetTaskRequest)(nil), "indent.v1.GetTaskRequest")
	proto.RegisterType((*CreateTaskRequest)(nil), "indent.v1.CreateTaskRequest")
	proto.RegisterType((*UpdateTaskRequest)(nil), "indent.v1.UpdateTaskRequest")
	proto.RegisterType((*DeleteTaskRequest)(nil), "indent.v1.DeleteTaskRequest")
	proto.RegisterType((*TaskPetitionDetails)(nil), "indent.v1.TaskPetitionDetails")
	proto.RegisterType((*Task)(nil), "indent.v1.Task")
}

func init() {
	proto.RegisterFile("indent/v1/task_api.proto", fileDescriptor_947671edfa2a898b)
}

var fileDescriptor_947671edfa2a898b = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xc6, 0xf9, 0x21, 0xf1, 0x09, 0x17, 0x92, 0xb9, 0x5c, 0xc9, 0x09, 0x7f, 0xb9, 0x46, 0x48,
	0x01, 0x74, 0x13, 0x85, 0x4b, 0x37, 0x74, 0x55, 0x08, 0x6d, 0x23, 0x68, 0x92, 0x9a, 0xf2, 0xa3,
	0xaa, 0x52, 0x34, 0x4d, 0xa6, 0x61, 0x44, 0x6c, 0x0f, 0x1e, 0x83, 0x54, 0x10, 0x9b, 0xbe, 0x42,
	0xdf, 0xa0, 0xcb, 0xaa, 0x0f, 0xd1, 0x75, 0xb7, 0x7d, 0x85, 0x3e, 0x48, 0x35, 0x63, 0x27, 0x4e,
	0x6c, 0x4a, 0x41, 0xea, 0xce, 0x3e, 0xe7, 0xcc, 0xf7, 0x7d, 0x67, 0xce, 0xcf, 0x80, 0x46, 0xad,
	0x2e, 0xb1, 0xdc, 0xca, 0x65, 0xb5, 0xe2, 0x62, 0x7e, 0xd6, 0xc6, 0x8c, 0x96, 0x99, 0x63, 0xbb,
	0x36, 0x52, 0x3d, 0x4f, 0xf9, 0xb2, 0x5a, 0x98, 0xef, 0xd9, 0x76, 0xaf, 0x4f, 0x2a, 0x98, 0xd1,
	0x0a, 0xb6, 0x2c, 0xdb, 0xc5, 0x2e, 0xb5, 0x2d, 0xee, 0x05, 0x16, 0x96, 0x7c, 0x08, 0x7c, 0xd1,
	0xa5, 0x12, 0xc8, 0x21, 0xdc, 0xbe, 0x70, 0x3a, 0x64, 0x10, 0x90, 0x0f, 0x38, 0x42, 0x2e, 0xbd,
	0x0b, 0xd9, 0x7d, 0xca, 0xdd, 0x57, 0x98, 0x9f, 0x71, 0x83, 0x9c, 0x5f, 0x10, 0xee, 0xa2, 0x05,
	0x00, 0xce, 0x70, 0x87, 0xb4, 0x2d, 0x6c, 0x12, 0x4d, 0x29, 0x2a, 0x25, 0xd5, 0x50, 0xa5, 0xa5,
	0x81, 0x4d, 0x82, 0xe6, 0x40, 0x65, 0xb8, 0x47, 0xda, 0x9c, 0x5e, 0x11, 0x2d, 0x56, 0x54, 0x4a,
	0x49, 0x23, 0x2d, 0x0c, 0x07, 0xf4, 0x8a, 0xa0, 0x59, 0x48, 0x62, 0xd3, 0xb6, 0x7a, 0x5a, 0xa2,
	0x18, 0x2f, 0xa9, 0x86, 0xf7, 0xa3, 0x6f, 0x41, 0x6e, 0x84, 0x85, 0x33, 0xdb, 0xe2, 0x04, 0xad,
	0x40, 0x52, 0x64, 0xcc, 0x35, 0xa5, 0x18, 0x2f, 0x65, 0x36, 0x66, 0xca, 0xc3, 0x7c, 0xcb, 0x22,
	0xd0, 0xf0, 0xbc, 0xfa, 0x3e, 0x4c, 0x3f, 0x23, 0xf2, 0xe8, 0xfd, 0xf5, 0xc9, 0x9b, 0x94, 0xde,
	0xa4, 0xf4, 0xa6, 0x85, 0x41, 0x38, 0xf5, 0x63, 0xc8, 0xed, 0x38, 0x04, 0xbb, 0xe4, 0x01, 0x80,
	0xcb, 0x90, 0x10, 0xe7, 0x25, 0xd6, 0x2d, 0x3a, 0xa5, 0x53, 0x77, 0x21, 0x77, 0xc8, 0xba, 0x0f,
	0x03, 0xbe, 0x4b, 0xe9, 0x90, 0x15, 0xee, 0x62, 0x6d, 0x42, 0xae, 0x46, 0xfa, 0xe4, 0x8f, 0xb1,
	0xea, 0x7b, 0xf0, 0xb7, 0x80, 0x6a, 0x11, 0x97, 0x8a, 0x16, 0xab, 0x11, 0x17, 0xd3, 0x3e, 0x17,
	0x65, 0xe5, 0x1d, 0x9b, 0x0d, 0xd0, 0xbc, 0x1f, 0xb4, 0x08, 0xc0, 0xfc, 0xc0, 0x7a, 0x4d, 0xb6,
	0x82, 0x6a, 0x8c, 0x58, 0xf4, 0xaf, 0x71, 0x48, 0x08, 0x34, 0x84, 0x20, 0x31, 0xa2, 0x45, 0x7e,
	0x87, 0x54, 0x26, 0xc3, 0x2a, 0x57, 0x21, 0x61, 0x12, 0x17, 0x6b, 0x33, 0x32, 0xfd, 0x7f, 0x06,
	0xe9, 0xcb, 0x1e, 0x17, 0x97, 0xf0, 0x82, 0xb8, 0xd8, 0x90, 0x21, 0xe8, 0x5f, 0x98, 0xea, 0x52,
	0xce, 0xfa, 0xf8, 0xbd, 0x87, 0x35, 0x2b, 0xb1, 0x32, 0xbe, 0x4d, 0xa2, 0x15, 0x21, 0xd3, 0x25,
	0xbc, 0xe3, 0x50, 0x26, 0xa4, 0x69, 0x79, 0x3f, 0x22, 0x30, 0xa1, 0x47, 0x90, 0xc6, 0x9c, 0xd3,
	0x9e, 0x45, 0x88, 0xb6, 0x28, 0x39, 0xf3, 0x11, 0x4e, 0xc3, 0x1f, 0x1e, 0x63, 0x18, 0x8a, 0xd6,
	0x21, 0xc9, 0x4e, 0x31, 0x27, 0xda, 0x72, 0x51, 0x29, 0x4d, 0x07, 0x3a, 0xfd, 0x32, 0x95, 0x5b,
	0xc2, 0x69, 0x78, 0x31, 0xa2, 0xa4, 0xef, 0x6c, 0xc7, 0xd4, 0x4a, 0x91, 0x92, 0x3e, 0xb5, 0x1d,
	0xd3, 0x90, 0x4e, 0xb4, 0x07, 0xd9, 0xc1, 0x15, 0xb6, 0xbb, 0xde, 0xf5, 0x6b, 0xff, 0xc9, 0x03,
	0x8b, 0x21, 0xf0, 0x50, 0x91, 0x9e, 0x4f, 0x18, 0x33, 0x6c, 0xdc, 0xa4, 0x6f, 0x42, 0x52, 0x2a,
	0x40, 0x19, 0x48, 0x1d, 0x36, 0xf6, 0x1a, 0xcd, 0xe3, 0x46, 0x76, 0x02, 0xa5, 0x21, 0xd1, 0x6c,
	0xed, 0x36, 0xb2, 0x0a, 0x02, 0x98, 0xdc, 0xd9, 0x6f, 0x1e, 0xec, 0xd6, 0xb2, 0x31, 0x61, 0xad,
	0x35, 0x1b, 0xbb, 0xd9, 0xf8, 0xb6, 0x0a, 0x29, 0x9f, 0x79, 0xe3, 0x4b, 0x02, 0x52, 0x82, 0xeb,
	0x49, 0xab, 0x8e, 0x4c, 0x50, 0x87, 0x53, 0x8c, 0xe6, 0x46, 0xc4, 0x84, 0x37, 0x48, 0x61, 0xfe,
	0x76, 0xa7, 0x37, 0xf8, 0xfa, 0xca, 0x87, 0xef, 0x3f, 0x3e, 0xc6, 0x96, 0xd0, 0x82, 0x58, 0x48,
	0xb2, 0xe2, 0xbc, 0x72, 0x1d, 0xf4, 0xc2, 0x8d, 0x5c, 0x84, 0x1c, 0x9d, 0x42, 0xca, 0x1f, 0x7c,
	0x94, 0x1f, 0xc1, 0x1b, 0x5f, 0x06, 0x85, 0xf0, 0x60, 0xe8, 0x55, 0x89, 0xbe, 0x8e, 0x56, 0xef,
	0x44, 0xaf, 0x5c, 0x0f, 0x67, 0xe0, 0x06, 0x11, 0x80, 0x60, 0x29, 0xa0, 0x51, 0xf1, 0x91, 0x5d,
	0x11, 0xe5, 0x2b, 0x49, 0x3e, 0x7d, 0x4b, 0x59, 0xd3, 0x7f, 0x93, 0xd0, 0x39, 0x40, 0xb0, 0x22,
	0xc6, 0x68, 0x22, 0x9b, 0x23, 0x4a, 0xb3, 0x29, 0x69, 0xca, 0x5b, 0xca, 0xda, 0xc6, 0x03, 0x32,
	0xb3, 0x00, 0x82, 0xfd, 0x30, 0x46, 0x19, 0x59, 0x1b, 0xbf, 0xbc, 0xc9, 0xb5, 0xfb, 0xf3, 0x6d,
	0xbf, 0x84, 0xbf, 0x3a, 0xb6, 0x19, 0x00, 0x6d, 0x4f, 0xc9, 0xe6, 0x61, 0xb4, 0x25, 0x5e, 0x9b,
	0x96, 0xf2, 0x1a, 0x0d, 0x9f, 0xa2, 0xc7, 0xde, 0xd7, 0x65, 0xf5, 0x53, 0x2c, 0x5e, 0x3f, 0x39,
	0xf9, 0x1c, 0x53, 0xeb, 0xde, 0xa9, 0xa3, 0xea, 0xb7, 0xc1, 0xf7, 0x9b, 0xa3, 0xea, 0xdb, 0x49,
	0xf9, 0x50, 0xfd, 0xff, 0x33, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x78, 0x8e, 0x69, 0x29, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TaskAPIClient is the client API for TaskAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskAPIClient interface {
	// List the Tasks within a space.
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// Retrieve specified Task by name.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// Create a new Task.
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// Update configuration of a Task.
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// Permanently destroy a Task.
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*Task, error)
}

type taskAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskAPIClient(cc grpc.ClientConnInterface) TaskAPIClient {
	return &taskAPIClient{cc}
}

func (c *taskAPIClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/indent.v1.TaskAPI/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAPIClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/indent.v1.TaskAPI/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAPIClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/indent.v1.TaskAPI/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAPIClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/indent.v1.TaskAPI/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAPIClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/indent.v1.TaskAPI/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskAPIServer is the server API for TaskAPI service.
type TaskAPIServer interface {
	// List the Tasks within a space.
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// Retrieve specified Task by name.
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	// Create a new Task.
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	// Update configuration of a Task.
	UpdateTask(context.Context, *UpdateTaskRequest) (*Task, error)
	// Permanently destroy a Task.
	DeleteTask(context.Context, *DeleteTaskRequest) (*Task, error)
}

// UnimplementedTaskAPIServer can be embedded to have forward compatible implementations.
type UnimplementedTaskAPIServer struct {
}

func (*UnimplementedTaskAPIServer) ListTasks(ctx context.Context, req *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (*UnimplementedTaskAPIServer) GetTask(ctx context.Context, req *GetTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedTaskAPIServer) CreateTask(ctx context.Context, req *CreateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedTaskAPIServer) UpdateTask(ctx context.Context, req *UpdateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (*UnimplementedTaskAPIServer) DeleteTask(ctx context.Context, req *DeleteTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}

func RegisterTaskAPIServer(s *grpc.Server, srv TaskAPIServer) {
	s.RegisterService(&_TaskAPI_serviceDesc, srv)
}

func _TaskAPI_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAPIServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.TaskAPI/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAPIServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAPI_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAPIServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.TaskAPI/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAPIServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAPI_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAPIServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.TaskAPI/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAPIServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAPI_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAPIServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.TaskAPI/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAPIServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAPI_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAPIServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indent.v1.TaskAPI/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAPIServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "indent.v1.TaskAPI",
	HandlerType: (*TaskAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTasks",
			Handler:    _TaskAPI_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskAPI_GetTask_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _TaskAPI_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskAPI_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskAPI_DeleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indent/v1/task_api.proto",
}
