name: build-clients
on:
  pull_request:
    paths:
    - "api/**"
    - "pkg/auditv1/**"
    - ".github/**"
  push:
    branches:
    - master
    paths:
    - "api/**"
    - "pkg/auditv1/**"
    - ".github/**"
jobs:
  build:
    name: clients.go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: make test
    - name: Build package
      run: make build
